# Generated by Django 4.2.16 on 2025-10-07 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="site_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_sites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Начальник участка",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники проекта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("project", "name")},
        ),
    ]
