# Generated by Django 4.2.16 on 2025-10-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_drawing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
            },
        ),
    ]
