# Generated by Django 4.2.16 on 2025-10-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_approved"),
        ("projects", "0004_alter_project_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                help_text="Компания-владелец проекта",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.company",
                verbose_name="Компания",
            ),
        ),
    ]
