--
-- PostgreSQL database dump
--

\restrict 15EMXkeriOpQQKmdZdq4hB0QUjebK5sUKmTpevyUku6MXfeZSG7tv9gdpIKLfs2

-- Dumped from database version 15.14
-- Dumped by pg_dump version 15.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: core_button_access; Type: TABLE DATA; Schema: public; Owner: checksite_user
--

INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (5, 'projects', 'export_excel', 'Экспорт Excel', 'Экспорт проектов в Excel', false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, '2025-11-01 20:09:03.081403+00', '2025-11-09 06:49:51.166204+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (45, 'supervisions', 'create', 'Создать надзор', 'Право на создание нового надзора', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.118626+00', '2025-11-11 14:18:47.954033+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (22, 'issues', 'delete', 'Удалить замечание', 'Право на удаление замечания', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.097347+00', '2025-11-11 14:18:47.937522+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (27, 'issues', 'view_details', 'Просмотр деталей', 'Просмотр подробной информации о замечании', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-01 20:09:03.101768+00', '2025-11-09 06:49:51.161059+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (20, 'issues', 'create', 'Создать замечание', 'Право на создание нового замечания', false, true, true, true, true, false, true, true, false, true, false, true, false, false, false, '2025-11-01 20:09:03.095644+00', '2025-11-11 14:18:47.934979+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (21, 'issues', 'edit', 'Редактировать замечание', 'Право на редактирование замечания', false, true, true, true, true, false, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.096505+00', '2025-11-11 14:18:47.936447+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (25, 'issues', 'add_comment', 'Добавить комментарий', 'Право на добавление комментариев к замечанию', false, true, true, true, true, true, true, true, false, true, true, true, false, false, false, '2025-11-01 20:09:03.100034+00', '2025-11-11 14:18:47.94104+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (6, 'projects', 'import_excel', 'Импорт Excel', 'Импорт проектов из Excel', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-01 20:09:03.082458+00', '2025-11-09 06:49:51.166962+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (44, 'tenders', 'submit_bid', 'Подать заявку', 'Подача заявки на участие в тендере', false, true, true, true, true, true, true, true, false, false, false, false, true, false, false, '2025-11-01 20:09:03.117791+00', '2025-11-09 06:49:51.173707+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (18, 'contractors', 'import_excel', 'Импорт Excel', 'Импорт подрядчиков из Excel', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-01 20:09:03.093703+00', '2025-11-09 06:49:51.15221+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (10, 'users', 'export_excel', 'Экспорт Excel', 'Экспорт сотрудников в Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.086248+00', '2025-11-09 06:49:51.177054+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (19, 'contractors', 'view_details', 'Просмотр деталей', 'Просмотр информации о подрядчике', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-01 20:09:03.094723+00', '2025-11-09 06:49:51.153332+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (46, 'supervisions', 'edit', 'Редактировать надзор', 'Право на редактирование данных надзора', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.119718+00', '2025-11-11 14:18:47.954722+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (40, 'tenders', 'create', 'Создать тендер', 'Право на создание тендера', false, true, true, true, true, false, false, false, false, false, false, false, true, false, false, '2025-11-01 20:09:03.11422+00', '2025-11-11 14:18:47.963407+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (41, 'tenders', 'edit', 'Редактировать тендер', 'Право на редактирование тендера', false, true, true, true, true, false, false, false, false, false, false, false, true, false, false, '2025-11-01 20:09:03.115162+00', '2025-11-11 14:18:47.96416+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (24, 'issues', 'assign', 'Назначить исполнителя', 'Назначение исполнителя на замечание', false, true, true, true, true, true, true, true, true, true, false, true, false, false, false, '2025-11-01 20:09:03.099141+00', '2025-11-09 06:49:51.157368+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (42, 'tenders', 'delete', 'Удалить тендер', 'Право на удаление тендера', false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.116105+00', '2025-11-11 14:18:47.964997+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (1, 'projects', 'create', 'Создать проект', 'Право на создание нового проекта', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.075492+00', '2025-11-11 14:18:47.941894+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (48, 'supervisions', 'export_excel', 'Экспорт Excel', 'Экспорт надзоров в Excel', false, true, true, true, true, true, true, true, false, true, false, true, false, false, false, '2025-11-01 20:09:03.121496+00', '2025-11-09 06:56:48.953548+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (3, 'projects', 'delete', 'Удалить проект', 'Право на удаление проекта', false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.078972+00', '2025-11-11 14:18:47.943508+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (7, 'users', 'create', 'Создать сотрудника', 'Право на создание нового сотрудника', false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.083454+00', '2025-11-11 14:18:47.945816+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (8, 'users', 'edit', 'Редактировать сотрудника', 'Право на редактирование данных сотрудника', false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.084416+00', '2025-11-11 14:18:47.946535+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (9, 'users', 'delete', 'Удалить сотрудника', 'Право на удаление сотрудника', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.085364+00', '2025-11-11 14:18:47.947227+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (17, 'contractors', 'export_excel', 'Экспорт Excel', 'Экспорт подрядчиков в Excel', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-01 20:09:03.092782+00', '2025-11-09 06:49:51.151015+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (23, 'issues', 'change_status', 'Изменить статус', 'Изменение статуса замечания', false, true, true, true, true, true, true, true, true, true, false, true, false, false, false, '2025-11-01 20:09:03.098198+00', '2025-11-09 06:49:51.157769+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (4, 'projects', 'view_details', 'Просмотр деталей', 'Просмотр подробной информации о проекте', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-01 20:09:03.080277+00', '2025-11-09 06:49:51.167309+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (11, 'users', 'import_excel', 'Импорт Excel', 'Импорт сотрудников из Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.087118+00', '2025-11-09 06:49:51.177675+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (13, 'users', 'view_details', 'Просмотр профиля', 'Просмотр профиля сотрудника', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-01 20:09:03.088836+00', '2025-11-09 06:49:51.178705+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (171, 'contractors', 'deactivate', 'Деактивировать подрядчика', 'Деактивация подрядчика (is_active=False)', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-06 15:06:56.192559+00', '2025-11-09 06:49:51.148523+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (173, 'contractors', 'restore', 'Восстановить', 'Восстановление подрядчика из архива', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-06 15:06:56.194226+00', '2025-11-09 06:49:51.152762+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (57, 'issues', 'send_to_review', 'Отправить на проверку', 'Отправка замечания на проверку ИТР или Надзору', false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, '2025-11-02 13:34:38.091147+00', '2025-11-09 06:49:51.160245+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (168, 'users', 'archive', 'В архив', 'Перемещение сотрудника в архив', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.190055+00', '2025-11-09 06:49:51.175269+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (58, 'issues', 'accept', 'Принять замечание', 'Право на принятие (завершение) замечания', false, true, true, true, true, false, true, true, false, true, false, true, false, false, false, '2025-11-02 13:34:38.092613+00', '2025-11-11 14:18:47.938403+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (50, 'supervisions', 'view_details', 'Просмотр деталей', 'Просмотр информации о надзоре', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-01 20:09:03.123289+00', '2025-11-09 06:49:51.170286+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (49, 'supervisions', 'import_excel', 'Импорт Excel', 'Импорт надзоров из Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.122316+00', '2025-11-09 06:56:48.954278+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (12, 'users', 'reset_password', 'Сбросить пароль', 'Сброс пароля пользователя', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.087982+00', '2025-11-09 06:49:51.178041+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (14, 'contractors', 'create', 'Создать подрядчика', 'Право на создание нового подрядчика', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.089775+00', '2025-11-11 14:18:47.950343+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (158, 'recycle-bin', 'clean_expired', 'Очистить просроченные', 'Удаление просроченных элементов из корзины', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-03 19:23:36.259413+00', '2025-11-09 06:49:51.167653+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (164, 'tasks', 'complete', 'Завершить задачу', 'Отметить задачу как выполненную', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-05 15:59:06.099695+00', '2025-11-09 06:49:51.17063+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (56, 'issues', 'add_photo_after', 'Добавить фото ПОСЛЕ', 'Загрузка фотографий "После" к замечанию', false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, '2025-11-02 12:41:04.155731+00', '2025-11-09 06:49:51.156427+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (175, 'supervisions', 'deactivate', 'Деактивировать надзор', 'Деактивация надзора (is_active=False)', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.196203+00', '2025-11-09 06:56:48.951855+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (172, 'contractors', 'archive', 'В архив', 'Перемещение подрядчика в архив (требуется перед удалением)', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-06 15:06:56.193385+00', '2025-11-09 06:49:51.147167+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (166, 'users', 'deactivate', 'Деактивировать сотрудника', 'Деактивация сотрудника (is_active=False)', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.188034+00', '2025-11-09 06:49:51.175869+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (170, 'contractors', 'activate', 'Активировать подрядчика', 'Активация подрядчика (is_active=True)', false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, '2025-11-06 15:06:56.191747+00', '2025-11-09 06:49:51.145367+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (165, 'users', 'activate', 'Активировать сотрудника', 'Активация сотрудника (is_active=True)', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.184471+00', '2025-11-09 06:49:51.17458+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (55, 'issues', 'add_photo_before', 'Добавить фото ДО', 'Загрузка фотографий "До" к замечанию', false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, '2025-11-02 12:41:04.154604+00', '2025-11-09 06:49:51.15684+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (157, 'issues', 'mark_accepted', 'Отметить принято', 'Поле "Принято" для отметки выполнения замечания ИТР', false, true, true, true, true, true, true, true, true, true, false, true, false, false, false, '2025-11-03 19:22:25.964984+00', '2025-11-09 06:49:51.15936+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (169, 'users', 'restore', 'Восстановить', 'Восстановление сотрудника из архива', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.19091+00', '2025-11-09 06:49:51.178378+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (174, 'supervisions', 'activate', 'Активировать надзор', 'Активация надзора (is_active=True)', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.195272+00', '2025-11-09 06:56:48.950237+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (115, 'tenders', 'view', 'Тендеры', 'Доступ к странице Тендеры', false, true, true, true, true, true, true, true, true, false, false, false, true, true, true, '2025-11-02 18:45:11.720239+00', '2025-11-09 06:49:51.185099+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (119, 'issues', 'reject', 'Отклонить замечание', 'Право на отклонение замечания', false, true, true, true, true, false, true, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.878821+00', '2025-11-11 14:18:47.939306+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (127, 'contractors', 'import', 'Импорт подрядчиков', 'Право на импорт данных подрядчиков из Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-02 19:26:20.895043+00', '2025-11-11 14:18:47.953301+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (124, 'users', 'import', 'Импорт персонала', 'Право на импорт данных персонала из Excel', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.890407+00', '2025-11-11 14:18:47.948887+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (120, 'issues', 'upload_photo', 'Загрузить фото', 'Право на загрузку фотографий к замечанию', false, true, true, true, true, false, true, true, false, true, true, true, false, false, false, '2025-11-02 19:26:20.879994+00', '2025-11-11 14:18:47.940284+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (134, 'settings', 'edit', 'Изменить настройки', 'Право на изменение настроек системы', false, true, true, true, true, false, true, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.910264+00', '2025-11-11 14:18:47.966347+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (138, 'dashboard', 'recycle_bin_delete', 'Окончательно удалить', 'Право на окончательное удаление элементов из корзины', false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.913295+00', '2025-11-11 14:18:47.969014+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (108, 'projects', 'view', 'Проекты', 'Доступ к странице Проекты', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.716433+00', '2025-11-09 06:49:51.183553+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (159, 'tasks', 'view', 'Задачи', 'Доступ к странице задач', false, true, true, true, true, true, true, true, true, false, false, false, true, true, true, '2025-11-05 15:59:06.094191+00', '2025-11-09 06:49:51.184777+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (2, 'projects', 'edit', 'Редактировать проект', 'Право на редактирование проекта', false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.077551+00', '2025-11-11 14:18:47.942728+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (128, 'supervisions', 'export', 'Экспорт надзоров', 'Право на экспорт данных надзоров в Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-02 19:26:20.898341+00', '2025-11-11 14:18:47.956292+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (121, 'projects', 'export', 'Экспорт проектов', 'Право на экспорт данных проектов в Excel', false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.885175+00', '2025-11-11 14:18:47.944292+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (125, 'users', 'approve', 'Одобрить пользователя', 'Право на одобрение регистрации пользователя', false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.891145+00', '2025-11-11 14:18:47.949638+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (15, 'contractors', 'edit', 'Редактировать подрядчика', 'Право на редактирование данных подрядчика', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-01 20:09:03.090869+00', '2025-11-11 14:18:47.951046+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (160, 'tasks', 'create', 'Создать задачу', 'Создание новой задачи для сотрудников и подрядчиков', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-05 15:59:06.096578+00', '2025-11-09 06:49:51.171002+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (135, 'settings', 'manage_access', 'Управление доступом', 'Право на управление матрицей доступа', false, true, true, true, true, false, true, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.911027+00', '2025-11-11 14:18:47.967008+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (136, 'dashboard', 'recycle_bin_access', 'Доступ к корзине', 'Право на просмотр корзины удалённых элементов', false, true, true, true, true, false, true, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.911823+00', '2025-11-11 14:18:47.967675+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (162, 'tasks', 'delete', 'Удалить задачу', 'Удаление задачи (soft delete)', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-05 15:59:06.098343+00', '2025-11-09 06:49:51.171349+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (161, 'tasks', 'edit', 'Редактировать задачу', 'Изменение задачи', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-05 15:59:06.097493+00', '2025-11-09 06:49:51.17171+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (163, 'tasks', 'reject', 'Отменить задачу', 'Отмена задачи с указанием причины', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-05 15:59:06.099061+00', '2025-11-09 06:49:51.172202+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (129, 'supervisions', 'import', 'Импорт надзоров', 'Право на импорт данных надзоров из Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-02 19:26:20.899151+00', '2025-11-11 14:18:47.957049+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (123, 'users', 'export', 'Экспорт персонала', 'Право на экспорт данных персонала в Excel', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.889635+00', '2025-11-11 14:18:47.948031+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (126, 'contractors', 'export', 'Экспорт подрядчиков', 'Право на экспорт данных подрядчиков в Excel', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-02 19:26:20.894349+00', '2025-11-11 14:18:47.952545+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (133, 'tenders', 'approve', 'Утвердить тендер', 'Право на утверждение тендера', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.909148+00', '2025-11-11 14:18:47.965687+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (137, 'dashboard', 'recycle_bin_restore', 'Восстановить из корзины', 'Право на восстановление элементов из корзины', false, true, true, true, true, false, true, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.912555+00', '2025-11-11 14:18:47.968343+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (111, 'contractors', 'view', 'Подрядчики', 'Доступ к странице Подрядчики', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.718174+00', '2025-11-09 06:49:51.182247+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (107, 'dashboard', 'view', 'Дашборд', 'Доступ к странице Дашборд', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.715607+00', '2025-11-09 06:49:51.182583+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (109, 'issues', 'view', 'Замечания', 'Доступ к странице Замечания', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.717092+00', '2025-11-09 06:49:51.182925+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (117, 'profile', 'view', 'Профиль', 'Доступ к странице Профиль', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.720954+00', '2025-11-09 06:50:58.769823+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (118, 'settings', 'view', 'Настройки', 'Доступ к странице Настройки', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.721253+00', '2025-11-09 06:49:51.183861+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (112, 'supervisions', 'view', 'Надзоры', 'Доступ к странице Надзоры', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.718702+00', '2025-11-09 06:49:51.184476+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (186, 'warehouse', 'create', 'Добавить на склад', 'Право на добавление товаров на склад', false, true, true, false, false, false, false, false, false, false, false, false, true, true, false, '2025-11-11 14:18:47.961378+00', '2025-11-11 14:18:47.961381+00', 'button', NULL, false, false);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (187, 'warehouse', 'edit', 'Редактировать товар', 'Право на редактирование товара на складе', false, true, true, false, false, false, false, false, false, false, false, false, true, true, false, '2025-11-11 14:18:47.96208+00', '2025-11-11 14:18:47.962083+00', 'button', NULL, false, false);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (188, 'warehouse', 'delete', 'Удалить товар', 'Право на удаление товара со склада', false, true, true, false, false, false, false, false, false, false, false, false, false, true, false, '2025-11-11 14:18:47.962766+00', '2025-11-11 14:18:47.962768+00', 'button', NULL, false, false);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (178, 'projects', 'add_drawing', 'Добавить чертёж', 'Право на добавление чертежей к проекту в формате PDF', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 16:15:30.290288+00', '2025-11-09 06:49:51.16393+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (179, 'projects', 'delete_drawing', 'Удалить чертёж', 'Право на удаление чертежей из проекта', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 16:15:30.291207+00', '2025-11-09 06:49:51.165128+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (43, 'tenders', 'view_details', 'Просмотр деталей', 'Просмотр подробной информации о тендере', false, true, true, true, true, true, true, true, true, false, false, false, true, true, true, '2025-11-01 20:09:03.116923+00', '2025-11-09 06:49:51.174068+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (110, 'users', 'view', 'Сотрудники', 'Доступ к странице Сотрудники', false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2025-11-02 18:45:11.717662+00', '2025-11-09 06:49:51.185384+00', 'page', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (176, 'supervisions', 'archive', 'В архив', 'Перемещение надзора в архив (требуется перед удалением)', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.19713+00', '2025-11-09 06:56:48.950825+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (177, 'supervisions', 'restore', 'Восстановить', 'Восстановление надзора из архива', false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, '2025-11-06 15:06:56.198212+00', '2025-11-09 06:56:48.954592+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (122, 'projects', 'import', 'Импорт проектов', 'Право на импорт данных проектов из Excel', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-02 19:26:20.886039+00', '2025-11-11 14:18:47.945078+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (16, 'contractors', 'delete', 'Удалить подрядчика', 'Право на удаление подрядчика', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.091889+00', '2025-11-11 14:18:47.951732+00', 'button', NULL, true, true);
INSERT INTO public.core_button_access (id, page, button_key, button_name, description, default_access, "SUPERADMIN", "DIRECTOR", "CHIEF_ENGINEER", "PROJECT_MANAGER", "ENGINEER", "SITE_MANAGER", "FOREMAN", "MASTER", "SUPERVISOR", "CONTRACTOR", "OBSERVER", "SUPPLY_MANAGER", "WAREHOUSE_HEAD", "SITE_WAREHOUSE_MANAGER", created_at, updated_at, access_type, company_id, "CHIEF_POWER_ENGINEER", "POWER_ENGINEER") VALUES (47, 'supervisions', 'delete', 'Удалить надзор', 'Право на удаление надзора', false, true, true, true, true, false, false, false, false, false, false, false, false, false, false, '2025-11-01 20:09:03.120651+00', '2025-11-11 14:18:47.955525+00', 'button', NULL, true, true);


--
-- Name: core_button_access_id_seq; Type: SEQUENCE SET; Schema: public; Owner: checksite_user
--

SELECT pg_catalog.setval('public.core_button_access_id_seq', 190, true);


--
-- PostgreSQL database dump complete
--

\unrestrict 15EMXkeriOpQQKmdZdq4hB0QUjebK5sUKmTpevyUku6MXfeZSG7tv9gdpIKLfs2

