# Generated by Django 4.2.16 on 2025-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_company_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="legal_form",
            field=models.CharField(
                choices=[
                    ("LLC", "ТОО (Товарищество с ограниченной ответственностью)"),
                    ("JSC", "АО (Акционерное общество)"),
                    ("PE", "ИП (Индивидуальный предприниматель)"),
                    ("CJSC", "ЗАО (Закрытое акционерное общество)"),
                    ("OJSC", "ОАО (Открытое акционерное общество)"),
                    ("PARTNERSHIP", "Партнерство"),
                    ("COOPERATIVE", "Кооператив"),
                    ("STATE", "Государственное предприятие"),
                    ("OTHER", "Другое"),
                ],
                default="LLC",
                max_length=50,
                verbose_name="Организационно-правовая форма (ОПФ)",
            ),
        ),
    ]
