# Generated by Django 4.2.16 on 2025-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_company_legal_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="Разрешен ли доступ к странице пользователей",
                verbose_name="Одобрено",
            ),
        ),
    ]
