# Generated by Django 4.2.16 on 2025-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_password",
            field=models.CharField(
                blank=True,
                help_text="Пароль для передачи пользователю",
                max_length=255,
                null=True,
                verbose_name="Временный пароль",
            ),
        ),
    ]
