# Generated by Django 4.2.16 on 2025-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_temp_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Подрядчик перемещен в архив (soft delete)",
                verbose_name="В архиве",
            ),
        ),
    ]
