# Generated by Django 4.2.16 on 2025-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervision_company",
            field=models.CharField(
                blank=True,
                help_text="Название надзорной компании, из которой работает специалист (для Технадзора и Авторского надзора)",
                max_length=255,
                verbose_name="Надзорная компания",
            ),
        ),
    ]
