# Generated by Django 4.2.16 on 2025-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_supervision_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="legal_form",
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text='Укажите полное название компании с организационно-правовой формой (например: ТОО "СтройКомпани", LLC "BuildCorp")',
                max_length=255,
                verbose_name="Название компании",
            ),
        ),
    ]
