# Generated by Django 4.2.16 on 2025-10-16 17:38

from django.db import migrations


def normalize_existing_emails(apps, schema_editor):
    """Приводим все существующие email к нижнему регистру для case-insensitive входа."""
    User = apps.get_model('users', 'User')

    # Обновляем все email к нижнему регистру
    for user in User.objects.all():
        updated = False

        if user.email:
            lowercase_email = user.email.lower()
            if user.email != lowercase_email:
                user.email = lowercase_email
                updated = True

        if user.secondary_email:
            lowercase_secondary = user.secondary_email.lower()
            if user.secondary_email != lowercase_secondary:
                user.secondary_email = lowercase_secondary
                updated = True

        if updated:
            user.save(update_fields=['email', 'secondary_email'])


def reverse_normalize(apps, schema_editor):
    """Обратная миграция - ничего не делаем, так как нельзя восстановить исходный регистр."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_company_legal_form_alter_company_name"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_emails, reverse_normalize),
    ]
