# Generated by Django 4.2.16 on 2025-10-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_normalize_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Название компании для Подрядчиков, Технадзора и Авторского надзора (сторонние компании)",
                max_length=255,
                verbose_name="Название компании",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Компания заказчика/генподрядчика (только для своих сотрудников)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supervision_company",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Используйте поле company_name. Оставлено для обратной совместимости.",
                max_length=255,
                verbose_name="Надзорная компания (устарело)",
            ),
        ),
    ]
