# Generated by Django 4.2.16 on 2025-10-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_company_name_alter_user_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.AddField(
            model_name="user",
            name="external_company_name",
            field=models.CharField(
                blank=True,
                help_text="Название компании для Подрядчиков, Технадзора и Авторского надзора (сторонние компании)",
                max_length=255,
                verbose_name="Название сторонней компании",
            ),
        ),
    ]
