# Generated by Django 4.2.16 on 2025-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Суперадмин"),
                    ("DIRECTOR", "Директор"),
                    ("CHIEF_ENGINEER", "Главный инженер"),
                    ("PROJECT_MANAGER", "Руководитель проекта"),
                    ("ENGINEER", "Инженер ПТО"),
                    ("SITE_MANAGER", "Начальник участка"),
                    ("FOREMAN", "Прораб"),
                    ("MASTER", "Мастер"),
                    ("SUPERVISOR", "Технадзор"),
                    ("CONTRACTOR", "Подрядчик"),
                    ("OBSERVER", "Наблюдатель"),
                    ("SUPPLY_MANAGER", "Снабженец"),
                    ("WAREHOUSE_HEAD", "Зав.Центрсклада"),
                ],
                default="OBSERVER",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
