# Generated by Django 4.2.16 on 2025-10-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_add_site_warehouse_manager_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_attempts_with_temp_password",
            field=models.IntegerField(
                default=0,
                help_text="Количество входов с временным паролем (макс. 3)",
                verbose_name="Попытки входа с временным паролем",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_change_required",
            field=models.BooleanField(
                default=False,
                help_text="Пользователь должен сменить пароль при следующем входе",
                verbose_name="Требуется смена пароля",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="История изменений паролей с датами",
                verbose_name="История паролей",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="temp_password_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания временного пароля"
            ),
        ),
    ]
