# Generated by Django 4.2.16 on 2025-10-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_login_attempts_with_temp_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_full_access",
            field=models.BooleanField(
                default=False,
                help_text="Автоматический доступ ко всем страницам системы (для категории Руководство)",
                verbose_name="Полный доступ",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_company_owner",
            field=models.BooleanField(
                default=False,
                help_text="Первый зарегистрированный пользователь компании, имеющий полный контроль",
                verbose_name="Владелец компании",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_category",
            field=models.CharField(
                choices=[
                    ("MANAGEMENT", "Руководство"),
                    ("ITR_SUPPLY", "ИТР и снабжение"),
                ],
                default="ITR_SUPPLY",
                help_text="Категория, определяющая уровень доступа по умолчанию",
                max_length=50,
                verbose_name="Категория должности",
            ),
        ),
    ]
