# Generated by Django 4.2.16 on 2025-10-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_has_full_access_user_is_company_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approved_by_director",
            field=models.BooleanField(
                default=False,
                help_text="Разрешение от директора на управление импортом/экспортом персонала. Требуется для ролей: Начальник участка, Прораб",
                verbose_name="Одобрен директором",
            ),
        ),
    ]
