# Generated by Django 4.2.16 on 2025-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_approved_by_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="work_type",
            field=models.CharField(
                blank=True,
                help_text="Описание видов выполняемых работ для подрядчика",
                max_length=255,
                verbose_name="Вид работ",
            ),
        ),
    ]
