# Generated by Django 4.2.16 on 2025-11-01 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_archived_to_deleted(apps, schema_editor):
    """
    Переносит данные из поля archived в is_deleted.
    Если пользователь был archived=True, то is_deleted=True.
    """
    User = apps.get_model('users', 'User')

    # Переносим archived=True → is_deleted=True
    archived_users = User.objects.filter(archived=True)
    for user in archived_users:
        user.is_deleted = True

    # Массовое обновление
    User.objects.filter(archived=True).update(is_deleted=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_work_type"),
    ]

    operations = [
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Дата и время когда запись была удалена",
                null=True,
                verbose_name="Дата удаления",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, удаливший запись",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалил",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Запись помечена как удаленная (soft delete)",
                verbose_name="Удалено",
            ),
        ),
        # Переносим данные из archived в is_deleted
        migrations.RunPython(migrate_archived_to_deleted, migrations.RunPython.noop),
        # Удаляем старое поле archived
        migrations.RemoveField(
            model_name="user",
            name="archived",
        ),
    ]
