# Generated by Django 4.2.16 on 2025-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_user_archived_user_deleted_at_user_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Суперадмин"),
                    ("DIRECTOR", "Директор"),
                    ("CHIEF_ENGINEER", "Главный инженер"),
                    ("PROJECT_MANAGER", "Руководитель проекта"),
                    ("CHIEF_POWER_ENGINEER", "Главный энергетик"),
                    ("ENGINEER", "Инженер ПТО"),
                    ("SITE_MANAGER", "Начальник участка"),
                    ("FOREMAN", "Прораб"),
                    ("POWER_ENGINEER", "Энергетик"),
                    ("MASTER", "Мастер"),
                    ("SUPERVISOR", "Технадзор"),
                    ("CONTRACTOR", "Подрядчик"),
                    ("OBSERVER", "Наблюдатель"),
                    ("SUPPLY_MANAGER", "Снабженец"),
                    ("WAREHOUSE_HEAD", "Зав.Центрсклада"),
                    ("SITE_WAREHOUSE_MANAGER", "Завсклад объекта"),
                ],
                default="OBSERVER",
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
