# Generated by Django 4.2.16 on 2025-10-22 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0005_project_company"),
        ("material_requests", "0011_materialrequestitem_actual_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(
                        help_text="Дата и время фактического поступления материала на склад объекта",
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Фактическое количество материала, прибывшее на склад",
                        max_digits=10,
                        verbose_name="Количество прибывшее",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Единица измерения материала",
                        max_length=50,
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "waybill_number",
                    models.CharField(
                        blank=True,
                        help_text="Номер товарно-транспортной накладной",
                        max_length=100,
                        verbose_name="Номер ТТН",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Название компании-поставщика",
                        max_length=255,
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные заметки о поступлении (брак, несоответствия и т.д.)",
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "Соответствует"),
                            ("DAMAGED", "Повреждено"),
                            ("DEFECTIVE", "Брак"),
                            ("PARTIAL", "Частично годное"),
                        ],
                        default="GOOD",
                        help_text="Состояние материала при приемке",
                        max_length=20,
                        verbose_name="Статус качества",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "material_item",
                    models.ForeignKey(
                        help_text="Конкретная позиция материала из заявки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_receipts",
                        to="material_requests.materialrequestitem",
                        verbose_name="Позиция материала",
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_receipts",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка на материалы",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_receipts",
                        to="projects.project",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        help_text="Сотрудник, который принял материал на складе",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Принял на складе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поступление на склад",
                "verbose_name_plural": "Поступления на склад",
                "ordering": ["-receipt_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "receipt_date"],
                        name="warehouse_w_project_992556_idx",
                    ),
                    models.Index(
                        fields=["material_request", "receipt_date"],
                        name="warehouse_w_materia_dce0b3_idx",
                    ),
                    models.Index(
                        fields=["received_by"], name="warehouse_w_receive_d67193_idx"
                    ),
                ],
            },
        ),
    ]
