# Generated by Django 4.2.16 on 2025-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ButtonAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        help_text="Название страницы (projects, users, и т.д.)",
                        max_length=100,
                        verbose_name="Страница",
                    ),
                ),
                (
                    "button_key",
                    models.CharField(
                        help_text="Уникальный ключ кнопки (create, edit, delete, и т.д.)",
                        max_length=100,
                        verbose_name="Ключ кнопки",
                    ),
                ),
                (
                    "button_name",
                    models.CharField(
                        help_text="Отображаемое название кнопки",
                        max_length=200,
                        verbose_name="Название кнопки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание функционала кнопки",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "default_access",
                    models.BooleanField(
                        default=False,
                        help_text="Если отмечено, кнопка доступна всем ролям",
                        verbose_name="Доступ по умолчанию",
                    ),
                ),
                (
                    "SUPERADMIN",
                    models.BooleanField(default=True, verbose_name="Суперадмин"),
                ),
                (
                    "DIRECTOR",
                    models.BooleanField(default=False, verbose_name="Директор"),
                ),
                (
                    "CHIEF_ENGINEER",
                    models.BooleanField(default=False, verbose_name="Главный инженер"),
                ),
                (
                    "PROJECT_MANAGER",
                    models.BooleanField(
                        default=False, verbose_name="Руководитель проекта"
                    ),
                ),
                (
                    "ENGINEER",
                    models.BooleanField(default=False, verbose_name="Инженер ПТО"),
                ),
                (
                    "SITE_MANAGER",
                    models.BooleanField(
                        default=False, verbose_name="Начальник участка"
                    ),
                ),
                ("FOREMAN", models.BooleanField(default=False, verbose_name="Прораб")),
                ("MASTER", models.BooleanField(default=False, verbose_name="Мастер")),
                (
                    "SUPERVISOR",
                    models.BooleanField(default=False, verbose_name="Технадзор"),
                ),
                (
                    "CONTRACTOR",
                    models.BooleanField(default=False, verbose_name="Подрядчик"),
                ),
                (
                    "OBSERVER",
                    models.BooleanField(default=False, verbose_name="Наблюдатель"),
                ),
                (
                    "SUPPLY_MANAGER",
                    models.BooleanField(default=False, verbose_name="Снабженец"),
                ),
                (
                    "WAREHOUSE_HEAD",
                    models.BooleanField(
                        default=False, verbose_name="Заведующий склада"
                    ),
                ),
                (
                    "SITE_WAREHOUSE_MANAGER",
                    models.BooleanField(default=False, verbose_name="Завсклад объекта"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Доступ к кнопке",
                "verbose_name_plural": "Матрица доступа к кнопкам",
                "db_table": "core_button_access",
                "ordering": ["page", "button_key"],
                "unique_together": {("page", "button_key")},
            },
        ),
    ]
