# Generated by Django 4.2.16 on 2025-11-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_user_archived_user_deleted_at_user_deleted_by_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buttonaccess",
            options={
                "ordering": ["access_type", "page", "button_key"],
                "verbose_name": "Доступ к кнопке/странице",
                "verbose_name_plural": "Матрица доступа (кнопки и страницы)",
            },
        ),
        migrations.AlterUniqueTogether(
            name="buttonaccess",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="buttonaccess",
            name="access_type",
            field=models.CharField(
                choices=[("button", "Кнопка"), ("page", "Страница")],
                default="button",
                help_text="Кнопка (глобально) или Страница (для компании)",
                max_length=20,
                verbose_name="Тип доступа",
            ),
        ),
        migrations.AddField(
            model_name="buttonaccess",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Для страниц - обязательно. Для кнопок - должно быть NULL (глобальная настройка)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_controls",
                to="users.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="buttonaccess",
            name="button_key",
            field=models.CharField(
                help_text='Уникальный ключ кнопки (create, edit, delete, и т.д.) или "view" для страниц',
                max_length=100,
                verbose_name="Ключ кнопки",
            ),
        ),
        migrations.AlterField(
            model_name="buttonaccess",
            name="button_name",
            field=models.CharField(
                help_text="Отображаемое название кнопки или страницы",
                max_length=200,
                verbose_name="Название кнопки",
            ),
        ),
        migrations.AlterField(
            model_name="buttonaccess",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание функционала кнопки или страницы",
                verbose_name="Описание",
            ),
        ),
        migrations.AddIndex(
            model_name="buttonaccess",
            index=models.Index(
                fields=["access_type", "page"], name="core_button_access__61d9ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buttonaccess",
            index=models.Index(
                fields=["company", "page"], name="core_button_company_c915ee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="buttonaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("access_type", "button"), ("company__isnull", True)
                ),
                fields=("page", "button_key"),
                name="unique_button_access",
            ),
        ),
        migrations.AddConstraint(
            model_name="buttonaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("access_type", "page")),
                fields=("company", "page", "button_key"),
                name="unique_page_access",
            ),
        ),
    ]
