# Generated by Django 4.2.16 on 2025-11-02 18:15

from django.db import migrations


def migrate_pageaccess_to_buttonaccess(apps, schema_editor):
    """
    Миграция данных из PageAccess в ButtonAccess.

    НОВАЯ ЛОГИКА (глобальные настройки):
    1. Берем все записи из PageAccess
    2. Группируем их ТОЛЬКО по страницам (БЕЗ привязки к компаниям)
    3. Для каждой страницы создаем ОДНУ глобальную запись ButtonAccess (company=NULL)
    4. Устанавливаем права доступа на основе наиболее распространенных настроек
    """
    PageAccess = apps.get_model('settings', 'PageAccess')
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    # Собираем данные по страницам (игнорируем компании)
    from collections import defaultdict
    pages_data = defaultdict(lambda: defaultdict(int))

    # Подсчитываем, сколько раз каждая роль имела доступ к каждой странице
    total_companies = 0
    for page_access in PageAccess.objects.all():
        page = page_access.page
        role = page_access.role
        has_access = page_access.has_access

        if has_access:
            pages_data[page][role] += 1

        # Считаем количество компаний
        if page == 'dashboard':
            total_companies = max(total_companies, 1)

    # Если в базе нет данных PageAccess, используем настройки по умолчанию
    if not pages_data:
        total_companies = 1

    # Словарь для красивых названий страниц
    page_display_names = {
        'dashboard': 'Дашборд',
        'projects': 'Проекты',
        'issues': 'Замечания',
        'users': 'Сотрудники',
        'contractors': 'Подрядчики',
        'supervisions': 'Надзоры',
        'material-requests': 'Заявки',
        'warehouse': 'Склад',
        'tenders': 'Тендеры',
        'reports': 'Отчеты',
        'profile': 'Профиль',
        'settings': 'Настройки',
    }

    # Список всех страниц (на случай если в PageAccess нет записей)
    all_pages = list(page_display_names.keys())

    # Создаем глобальные записи ButtonAccess
    created_count = 0
    for page in all_pages:
        roles_access = pages_data.get(page, {})

        # Если нет данных в PageAccess, используем настройки по умолчанию для руководства
        # (аналогично категории "Руководство" из матрицы доступа)
        default_director_access = True
        default_chief_engineer_access = True
        default_project_manager_access = True

        # Создаем ОДНУ глобальную запись для этой страницы
        button_access = ButtonAccess(
            access_type='page',
            company=None,  # Глобальная настройка для всех компаний
            page=page,
            button_key='view',
            button_name=page_display_names.get(page, page.title()),
            description=f'Доступ к странице {page_display_names.get(page, page)}',
            default_access=False,
            # Устанавливаем права для каждой роли
            SUPERADMIN=True,
            # Если больше половины компаний давали доступ - даем доступ глобально
            DIRECTOR=roles_access.get('DIRECTOR', 0) > (total_companies / 2) if total_companies > 0 else default_director_access,
            CHIEF_ENGINEER=roles_access.get('CHIEF_ENGINEER', 0) > (total_companies / 2) if total_companies > 0 else default_chief_engineer_access,
            PROJECT_MANAGER=roles_access.get('PROJECT_MANAGER', 0) > (total_companies / 2) if total_companies > 0 else default_project_manager_access,
            ENGINEER=roles_access.get('ENGINEER', 0) > (total_companies / 2) if total_companies > 0 else False,
            SITE_MANAGER=roles_access.get('SITE_MANAGER', 0) > (total_companies / 2) if total_companies > 0 else False,
            FOREMAN=roles_access.get('FOREMAN', 0) > (total_companies / 2) if total_companies > 0 else False,
            MASTER=roles_access.get('MASTER', 0) > (total_companies / 2) if total_companies > 0 else False,
            SUPERVISOR=roles_access.get('SUPERVISOR', 0) > (total_companies / 2) if total_companies > 0 else False,
            CONTRACTOR=roles_access.get('CONTRACTOR', 0) > (total_companies / 2) if total_companies > 0 else False,
            OBSERVER=roles_access.get('OBSERVER', 0) > (total_companies / 2) if total_companies > 0 else False,
            SUPPLY_MANAGER=roles_access.get('SUPPLY_MANAGER', 0) > (total_companies / 2) if total_companies > 0 else False,
            WAREHOUSE_HEAD=roles_access.get('WAREHOUSE_HEAD', 0) > (total_companies / 2) if total_companies > 0 else False,
            SITE_WAREHOUSE_MANAGER=roles_access.get('SITE_WAREHOUSE_MANAGER', 0) > (total_companies / 2) if total_companies > 0 else False,
        )
        button_access.save()
        created_count += 1

    print(f'✅ Создано {created_count} глобальных записей страниц в ButtonAccess')


def reverse_migration(apps, schema_editor):
    """
    Откат миграции - удаляем все записи ButtonAccess с access_type='page'
    """
    ButtonAccess = apps.get_model('core', 'ButtonAccess')
    deleted_count = ButtonAccess.objects.filter(access_type='page').count()
    ButtonAccess.objects.filter(access_type='page').delete()
    print(f'🔄 Удалено {deleted_count} записей ButtonAccess с типом "page"')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_page_support_to_buttonaccess"),
        ("settings", "0004_remove_technical_conditions"),
    ]

    operations = [
        migrations.RunPython(
            migrate_pageaccess_to_buttonaccess,
            reverse_migration
        ),
    ]
