# Generated by Django 4.2.16 on 2025-11-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_user_archived_user_deleted_at_user_deleted_by_and_more"),
        ("core", "0003_migrate_pageaccess_to_buttonaccess"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="buttonaccess",
            name="unique_button_access",
        ),
        migrations.RemoveConstraint(
            model_name="buttonaccess",
            name="unique_page_access",
        ),
        migrations.AlterField(
            model_name="buttonaccess",
            name="access_type",
            field=models.CharField(
                choices=[("button", "Кнопка"), ("page", "Страница")],
                default="button",
                help_text="Кнопка или Страница (оба типа - глобальные настройки)",
                max_length=20,
                verbose_name="Тип доступа",
            ),
        ),
        migrations.AlterField(
            model_name="buttonaccess",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Должно быть NULL. Все настройки - глобальные.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_controls",
                to="users.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddConstraint(
            model_name="buttonaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", True)),
                fields=("page", "button_key"),
                name="unique_global_access",
            ),
        ),
    ]
