# Generated by Django 4.2.16 on 2025-11-06 15:04

from django.db import migrations


def add_missing_buttons(apps, schema_editor):
    """
    Добавляет недостающие кнопки для управления пользователями, подрядчиками и надзорами.

    Кнопки добавляются для следующих ролей:
    - SUPERADMIN, DIRECTOR, CHIEF_ENGINEER, PROJECT_MANAGER (руководство)
    - SITE_MANAGER (начальник участка)

    Недостающие кнопки:
    - activate: активация пользователя/подрядчика/надзора
    - deactivate: деактивация пользователя/подрядчика/надзора
    - archive: перемещение в архив (для contractors и supervisions)
    - restore: восстановление из архива (для contractors и supervisions)
    - toggle_access: открытие/закрытие доступа (только для users)
    """
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    # Роли руководства + начальник участка
    management_roles = ['SUPERADMIN', 'DIRECTOR', 'CHIEF_ENGINEER', 'PROJECT_MANAGER', 'SITE_MANAGER']

    # Словарь с настройками кнопок
    buttons_config = {
        'users': [
            {
                'button_key': 'activate',
                'button_name': 'Активировать сотрудника',
                'description': 'Активация сотрудника (is_active=True)',
                'roles': management_roles
            },
            {
                'button_key': 'deactivate',
                'button_name': 'Деактивировать сотрудника',
                'description': 'Деактивация сотрудника (is_active=False)',
                'roles': management_roles
            },
            {
                'button_key': 'archive',
                'button_name': 'В архив',
                'description': 'Перемещение сотрудника в архив',
                'roles': management_roles
            },
            {
                'button_key': 'restore',
                'button_name': 'Восстановить',
                'description': 'Восстановление сотрудника из архива',
                'roles': management_roles
            },
        ],
        'contractors': [
            {
                'button_key': 'activate',
                'button_name': 'Активировать подрядчика',
                'description': 'Активация подрядчика (is_active=True)',
                'roles': management_roles
            },
            {
                'button_key': 'deactivate',
                'button_name': 'Деактивировать подрядчика',
                'description': 'Деактивация подрядчика (is_active=False)',
                'roles': management_roles
            },
            {
                'button_key': 'archive',
                'button_name': 'В архив',
                'description': 'Перемещение подрядчика в архив (требуется перед удалением)',
                'roles': management_roles
            },
            {
                'button_key': 'restore',
                'button_name': 'Восстановить',
                'description': 'Восстановление подрядчика из архива',
                'roles': management_roles
            },
        ],
        'supervisions': [
            {
                'button_key': 'activate',
                'button_name': 'Активировать надзор',
                'description': 'Активация надзора (is_active=True)',
                'roles': management_roles
            },
            {
                'button_key': 'deactivate',
                'button_name': 'Деактивировать надзор',
                'description': 'Деактивация надзора (is_active=False)',
                'roles': management_roles
            },
            {
                'button_key': 'archive',
                'button_name': 'В архив',
                'description': 'Перемещение надзора в архив (требуется перед удалением)',
                'roles': management_roles
            },
            {
                'button_key': 'restore',
                'button_name': 'Восстановить',
                'description': 'Восстановление надзора из архива',
                'roles': management_roles
            },
        ],
    }

    # Создаём кнопки для каждой страницы
    for page, buttons in buttons_config.items():
        for button_config in buttons:
            # Проверяем, не существует ли уже такая кнопка
            existing = ButtonAccess.objects.filter(
                page=page,
                button_key=button_config['button_key'],
                access_type='button',
                company__isnull=True
            ).first()

            if not existing:
                # Создаём словарь для ролей
                roles_dict = {role: True for role in button_config['roles']}

                ButtonAccess.objects.create(
                    access_type='button',
                    page=page,
                    button_key=button_config['button_key'],
                    button_name=button_config['button_name'],
                    description=button_config['description'],
                    default_access=False,
                    company=None,
                    # Устанавливаем роли
                    **roles_dict
                )
                print(f"✅ Создана кнопка: {page}.{button_config['button_key']} для ролей {button_config['roles']}")
            else:
                print(f"⏭️  Кнопка уже существует: {page}.{button_config['button_key']}")


def remove_buttons(apps, schema_editor):
    """Откат миграции - удаление добавленных кнопок."""
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    buttons_to_remove = [
        ('users', 'activate'),
        ('users', 'deactivate'),
        ('users', 'archive'),
        ('users', 'restore'),
        ('contractors', 'activate'),
        ('contractors', 'deactivate'),
        ('contractors', 'archive'),
        ('contractors', 'restore'),
        ('supervisions', 'activate'),
        ('supervisions', 'deactivate'),
        ('supervisions', 'archive'),
        ('supervisions', 'restore'),
    ]

    for page, button_key in buttons_to_remove:
        ButtonAccess.objects.filter(
            page=page,
            button_key=button_key,
            access_type='button',
            company__isnull=True
        ).delete()
        print(f"🗑️  Удалена кнопка: {page}.{button_key}")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_simplify_buttonaccess_constraints"),
    ]

    operations = [
        migrations.RunPython(add_missing_buttons, remove_buttons),
    ]
