# Generated by Django 4.2.16 on 2025-11-06 15:06

from django.db import migrations


def update_delete_buttons(apps, schema_editor):
    """
    Обновляет кнопку 'delete' для users, contractors, supervisions:
    Добавляет роль SITE_MANAGER (начальник участка) к существующим правам на удаление.

    Теперь удалять могут:
    - SUPERADMIN, DIRECTOR, CHIEF_ENGINEER, PROJECT_MANAGER, SITE_MANAGER
    """
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    pages = ['users', 'contractors', 'supervisions']

    for page in pages:
        try:
            delete_button = ButtonAccess.objects.get(
                page=page,
                button_key='delete',
                access_type='button',
                company__isnull=True
            )

            # Добавляем SITE_MANAGER к правам на удаление
            delete_button.SITE_MANAGER = True
            delete_button.save(update_fields=['SITE_MANAGER'])

            print(f"✅ Обновлена кнопка delete для {page}: добавлена роль SITE_MANAGER")
        except ButtonAccess.DoesNotExist:
            print(f"⚠️  Кнопка delete не найдена для {page}")


def revert_delete_buttons(apps, schema_editor):
    """Откат миграции - убираем SITE_MANAGER из прав на удаление."""
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    pages = ['users', 'contractors', 'supervisions']

    for page in pages:
        try:
            delete_button = ButtonAccess.objects.get(
                page=page,
                button_key='delete',
                access_type='button',
                company__isnull=True
            )

            # Убираем SITE_MANAGER из прав на удаление
            delete_button.SITE_MANAGER = False
            delete_button.save(update_fields=['SITE_MANAGER'])

            print(f"🔄 Откат: убрана роль SITE_MANAGER из кнопки delete для {page}")
        except ButtonAccess.DoesNotExist:
            print(f"⚠️  Кнопка delete не найдена для {page}")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_missing_user_management_buttons"),
    ]

    operations = [
        migrations.RunPython(update_delete_buttons, revert_delete_buttons),
    ]
