# Generated by Django 4.2.16 on 2025-11-06 16:13

from django.db import migrations


def add_drawing_buttons(apps, schema_editor):
    """
    Добавляет кнопки для работы с чертежами на странице projects.

    add_drawing: Директор, Главный инженер, Руководитель проекта,
                 Начальник участка, Инженер, Прораб (7 ролей)

    delete_drawing: Директор, Главный инженер, Руководитель проекта,
                    Начальник участка, Инженер (БЕЗ Прораба - 6 ролей)
    """
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    # Проверяем, не существуют ли уже эти кнопки
    if ButtonAccess.objects.filter(page='projects', button_key='add_drawing').exists():
        print("⚠️  Кнопка add_drawing уже существует, пропускаем")
    else:
        # Кнопка: Добавить чертёж
        ButtonAccess.objects.create(
            access_type='button',
            company=None,  # Глобальная настройка
            page='projects',
            button_key='add_drawing',
            button_name='Добавить чертёж',
            description='Право на добавление чертежей к проекту в формате PDF',
            default_access=False,
            SUPERADMIN=True,
            DIRECTOR=True,
            CHIEF_ENGINEER=True,
            PROJECT_MANAGER=True,
            SITE_MANAGER=True,
            ENGINEER=True,
            FOREMAN=True,  # Прораб МОЖЕТ добавлять чертежи
            MASTER=False,
            SUPERVISOR=False,
            CONTRACTOR=False,
            OBSERVER=False,
            SUPPLY_MANAGER=False,
            WAREHOUSE_HEAD=False,
            SITE_WAREHOUSE_MANAGER=False
        )
        print("✅ Создана кнопка add_drawing для projects")

    if ButtonAccess.objects.filter(page='projects', button_key='delete_drawing').exists():
        print("⚠️  Кнопка delete_drawing уже существует, пропускаем")
    else:
        # Кнопка: Удалить чертёж
        ButtonAccess.objects.create(
            access_type='button',
            company=None,  # Глобальная настройка
            page='projects',
            button_key='delete_drawing',
            button_name='Удалить чертёж',
            description='Право на удаление чертежей из проекта',
            default_access=False,
            SUPERADMIN=True,
            DIRECTOR=True,
            CHIEF_ENGINEER=True,
            PROJECT_MANAGER=True,
            SITE_MANAGER=True,
            ENGINEER=True,
            FOREMAN=False,  # Прораб НЕ МОЖЕТ удалять чертежи
            MASTER=False,
            SUPERVISOR=False,
            CONTRACTOR=False,
            OBSERVER=False,
            SUPPLY_MANAGER=False,
            WAREHOUSE_HEAD=False,
            SITE_WAREHOUSE_MANAGER=False
        )
        print("✅ Создана кнопка delete_drawing для projects")


def remove_drawing_buttons(apps, schema_editor):
    """Откатывает добавление кнопок для чертежей"""
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    deleted_count = ButtonAccess.objects.filter(
        page='projects',
        button_key__in=['add_drawing', 'delete_drawing']
    ).delete()[0]

    print(f"🔄 Откат: удалено {deleted_count} кнопок для чертежей")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_update_delete_button_add_site_manager"),
    ]

    operations = [
        migrations.RunPython(add_drawing_buttons, remove_drawing_buttons),
    ]
