# Generated by Django 5.0.6 on 2025-11-07 18:18

from django.db import migrations


def remove_reports_page_access(apps, schema_editor):
    """
    Удаляет все записи ButtonAccess для страницы 'reports'.
    Страница /dashboard/reports была полностью удалена из системы.
    """
    ButtonAccess = apps.get_model('core', 'ButtonAccess')

    # Удаляем все записи с page='reports'
    deleted_count, _ = ButtonAccess.objects.filter(page='reports').delete()

    # Логируем результат (будет виден при выполнении миграции)
    if deleted_count > 0:
        print(f"✅ Удалено {deleted_count} записей ButtonAccess для страницы 'reports'")
    else:
        print("ℹ️  Записи ButtonAccess для страницы 'reports' уже отсутствуют")


def restore_reports_page_access(apps, schema_editor):
    """
    Обратная миграция (откат).
    В данном случае ничего не делаем, т.к. восстанавливать записи не имеет смысла.
    """
    print("⚠️  Откат миграции: записи ButtonAccess для 'reports' НЕ восстанавливаются")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_drawing_buttons_to_projects"),
    ]

    operations = [
        migrations.RunPython(
            remove_reports_page_access,
            reverse_code=restore_reports_page_access
        ),
    ]
