# Generated by Django 4.2.16 on 2025-11-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_reports_page_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="buttonaccess",
            name="CHIEF_POWER_ENGINEER",
            field=models.BooleanField(default=False, verbose_name="Главный энергетик"),
        ),
        migrations.AddField(
            model_name="buttonaccess",
            name="POWER_ENGINEER",
            field=models.BooleanField(default=False, verbose_name="Энергетик"),
        ),
    ]
