# Generated by Django 4.2.16 on 2025-10-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание проблемы")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новое"),
                            ("IN_PROGRESS", "В процессе"),
                            ("PENDING_REVIEW", "На проверке"),
                            ("COMPLETED", "Исполнено"),
                            ("OVERDUE", "Просрочено"),
                            ("REJECTED", "Отклонено"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Критичное"),
                            ("HIGH", "Важное"),
                            ("NORMAL", "Обычное"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок устранения"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "correction_technology",
                    models.TextField(
                        blank=True,
                        help_text="Как должно быть исправлено",
                        verbose_name="Технология исправления",
                    ),
                ),
                (
                    "materials_used",
                    models.TextField(
                        blank=True, verbose_name="Использованные материалы"
                    ),
                ),
                (
                    "location_notes",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Примечания о местоположении",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Замечание",
                "verbose_name_plural": "Замечания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssuePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("BEFORE", "До"),
                            ("AFTER", "После"),
                            ("INSPECTION", "Осмотр"),
                        ],
                        default="BEFORE",
                        max_length=20,
                        verbose_name="Этап",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="issues/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="issues.issue",
                        verbose_name="Замечание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото замечания",
                "verbose_name_plural": "Фото замечаний",
                "ordering": ["stage", "created_at"],
            },
        ),
    ]
