# Generated by Django 4.2.16 on 2025-10-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="issuephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stage", "BEFORE")),
                fields=("issue", "stage"),
                name="unique_before_photo_per_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stage", "AFTER")),
                fields=("issue", "stage"),
                name="unique_after_photo_per_issue",
            ),
        ),
    ]
