# Generated by Django 4.2.16 on 2025-10-14 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0003_issuephoto_unique_before_photo_per_issue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecomment",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="read_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Прочитано пользователями",
            ),
        ),
    ]
