# Generated by Django 4.2.16 on 2025-10-18 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_project_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Номер заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("UNDER_REVIEW", "На проверке снабжения"),
                            ("WAREHOUSE_CHECK", "Проверка склада"),
                            ("RESERVED", "Резерв на складе"),
                            ("SUPPLIER_SEARCH", "Поиск поставщика"),
                            ("REGISTRY_APPROVAL", "Реестр на утверждении"),
                            ("INVOICE_SIGNING", "Счета на подпись"),
                            ("ACCOUNTING", "В бухгалтерии"),
                            ("DELIVERY", "Доставка"),
                            ("ACCEPTED", "Принято на объекте"),
                            ("COMPLETED", "Отработано"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "drawing_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на чертёж или номер листа",
                        max_length=255,
                        verbose_name="Чертёж / Лист",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Вид работ"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "author_signature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Фамилия, инициалы, подпись автора",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее действие"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор (Прораб)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to="projects.project",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на материалы",
                "verbose_name_plural": "Заявки на материалы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        help_text="Наименование материала (например: Арматура Ø12)",
                        max_length=255,
                        verbose_name="Материал",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="шт",
                        help_text="Единица измерения (кг, м, м², м³, шт и т.д.)",
                        max_length=50,
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "specifications",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные характеристики материала",
                        verbose_name="Спецификация",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция материала",
                "verbose_name_plural": "Позиции материалов",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Старый статус"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(max_length=30, verbose_name="Новый статус"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История заявки",
                "verbose_name_plural": "История заявок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("REGISTRY", "Реестр"),
                            ("INVOICE", "Счёт"),
                            ("WAYBILL", "ТТН"),
                            ("PHOTO", "Фото"),
                            ("OTHER", "Другое"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="material_requests/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ заявки",
                "verbose_name_plural": "Документы заявок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_material_request_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Прочитано пользователями",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к заявке",
                "verbose_name_plural": "Комментарии к заявкам",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["project", "status"], name="material_re_project_75b0e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["author", "created_at"], name="material_re_author__fb0d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["responsible"], name="material_re_respons_c0d0a0_idx"
            ),
        ),
    ]
