# Generated by Django 4.2.16 on 2025-11-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0020_alter_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_project_deleted_at_project_deleted_by_and_more"),
        ("tenders", "0006_fix_tenderbid_participant_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        editable=False,
                        help_text="Автогенерируемый номер в формате MR-YYYYMMDD-XXX",
                        max_length=50,
                        unique=True,
                        verbose_name="Номер заявки",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Краткое описание заявки",
                        max_length=255,
                        verbose_name="Название заявки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительное описание или комментарии к заявке",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("IN_APPROVAL", "На согласовании"),
                            ("APPROVED", "Согласована"),
                            ("IN_PAYMENT", "На оплате"),
                            ("IN_DELIVERY", "На доставке"),
                            ("COMPLETED", "Отработана и доставлена на объект"),
                            ("REJECTED", "На доработке"),
                        ],
                        default="DRAFT",
                        help_text="Текущий статус заявки",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "current_approval_role",
                    models.CharField(
                        blank=True,
                        help_text="Роль сотрудника, который должен согласовать заявку сейчас",
                        max_length=50,
                        null=True,
                        verbose_name="Текущая роль на согласовании",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается при создании",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Автоматически обновляется при изменении",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда заявка была отправлена на согласование",
                        null=True,
                        verbose_name="Дата отправки на согласование",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда директор согласовал заявку",
                        null=True,
                        verbose_name="Дата полного согласования",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда материалы были получены на объекте",
                        null=True,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Почему заявка была возвращена на доработку",
                        null=True,
                        verbose_name="Причина возврата",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Мягкое удаление",
                        verbose_name="Удалена",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Сотрудник, создавший заявку (Мастер, Прораб или Начальник участка)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор заявки",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Компания, создавшая заявку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to="users.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Проект, для которого создается заявка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто вернул на доработку",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на материалы",
                "verbose_name_plural": "Заявки на материалы",
                "db_table": "material_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Роль пользователя, который должен согласовать этот этап",
                        max_length=50,
                        verbose_name="Роль согласующего",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает согласования"),
                            ("APPROVED", "Согласовано"),
                            ("REJECTED", "Отклонено"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата согласования"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Согласовал",
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап согласования",
                "verbose_name_plural": "Этапы согласования",
                "db_table": "material_request_approval_steps",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        help_text="Название строительного материала",
                        max_length=255,
                        verbose_name="Название материала",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Единица измерения (шт, м, кг, л и т.д.)",
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Запрошенное количество материала",
                        max_digits=10,
                        verbose_name="Количество по заявке",
                    ),
                ),
                (
                    "quantity_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Фактически полученное количество (заполняется при получении)",
                        max_digits=10,
                        null=True,
                        verbose_name="Количество по факту",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные примечания к позиции",
                        null=True,
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "position_number",
                    models.PositiveIntegerField(
                        help_text="Порядковый номер позиции в заявке",
                        verbose_name="Номер позиции",
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        help_text="Заявка, к которой относится позиция",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        blank=True,
                        help_text="Тендер, если позиция была объявлена на тендер",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_items",
                        to="tenders.tender",
                        verbose_name="Тендер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявок",
                "db_table": "material_request_items",
                "ordering": ["position_number"],
                "indexes": [
                    models.Index(
                        fields=["material_request"],
                        name="material_re_materia_5e11db_idx",
                    ),
                    models.Index(
                        fields=["material_name"], name="material_re_materia_226992_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создана"),
                            ("SUBMITTED", "Отправлена на согласование"),
                            ("APPROVED", "Согласована"),
                            ("REJECTED", "Возвращена на доработку"),
                            ("PAYMENT", "Переведена на оплату"),
                            ("PAID", "Оплачена"),
                            ("DELIVERY", "Переведена на доставку"),
                            ("RECEIVED", "Материалы приняты"),
                            ("COMPLETED", "Завершена"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата действия"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительная информация о действии",
                        verbose_name="Детали",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_request_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История заявки",
                "verbose_name_plural": "История заявок",
                "db_table": "material_request_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["material_request"],
                        name="material_re_materia_115a25_idx",
                    ),
                    models.Index(
                        fields=["action"], name="material_re_action_5a6826_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="material_re_created_91e9d9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["request_number"], name="material_re_request_0c07dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(fields=["status"], name="material_re_status_6fcb1f_idx"),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["author"], name="material_re_author__b33259_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["project"], name="material_re_project_b3db8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["company"], name="material_re_company_f5fa99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["current_approval_role"], name="material_re_current_6ff634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["is_deleted"], name="material_re_is_dele_4dfa50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["material_request", "role"],
                name="material_re_materia_d3eaea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(fields=["status"], name="material_re_status_324582_idx"),
        ),
    ]
