# Generated by Django 4.2.16 on 2025-11-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0020_alter_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_project_deleted_at_project_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Удалено"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Автоматически генерируется: MR-2024-0001",
                        max_length=50,
                        unique=True,
                        verbose_name="Номер заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            (
                                "SITE_MANAGER_APPROVAL",
                                "На согласовании у Начальника участка",
                            ),
                            ("ENGINEER_APPROVAL", "На согласовании у Инженера ПТО"),
                            ("PM_APPROVAL", "На согласовании у Руководителя проекта"),
                            (
                                "CHIEF_POWER_APPROVAL",
                                "На согласовании у Главного энергетика",
                            ),
                            (
                                "CHIEF_ENGINEER_APPROVAL",
                                "На согласовании у Главного инженера",
                            ),
                            ("DIRECTOR_APPROVAL", "На согласовании у Директора"),
                            ("APPROVED", "Согласовано"),
                            ("WAREHOUSE_REVIEW", "Проверка наличия на складе"),
                            ("PROCUREMENT", "Поиск поставщиков"),
                            ("PAYMENT", "На оплате"),
                            ("DELIVERY", "На доставке"),
                            ("COMPLETED", "Отработано и доставлено"),
                            ("REJECTED", "Возвращена на доработку"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "current_approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Роль сотрудника, который должен согласовать сейчас",
                        max_length=50,
                        null=True,
                        verbose_name="Роль текущего согласующего",
                    ),
                ),
                (
                    "approval_chain",
                    models.JSONField(
                        default=list,
                        help_text="Список ролей для согласования в порядке следования",
                        verbose_name="Цепочка согласования",
                    ),
                ),
                (
                    "approval_chain_index",
                    models.IntegerField(
                        default=0,
                        help_text="Индекс текущего этапа в approval_chain",
                        verbose_name="Текущий индекс в цепочке",
                    ),
                ),
                (
                    "approval_history",
                    models.JSONField(
                        default=list,
                        help_text="Список всех действий по согласованию",
                        verbose_name="История согласования",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, verbose_name="Причина возврата на доработку"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата отправки на согласование",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата полного согласования"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата завершения (доставлено)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to="users.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор заявки",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Текущий согласующий",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Удалил",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_requests",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_material_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто вернул на доработку",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на материалы",
                "verbose_name_plural": "Заявки на материалы",
                "db_table": "material_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        help_text="Например: Цемент М500, Арматура А500С Ø12",
                        max_length=255,
                        verbose_name="Название материала",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Например: тонна, м³, шт., кг",
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Запрошенное количество",
                        max_digits=10,
                        verbose_name="Количество по заявке",
                    ),
                ),
                (
                    "quantity_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Фактически доставленное количество",
                        max_digits=10,
                        null=True,
                        verbose_name="Количество по факту",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о материале",
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция материала",
                "verbose_name_plural": "Позиции материалов",
                "db_table": "material_request_items",
                "ordering": ["request", "order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["company", "status"], name="material_re_company_e78f10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["project", "status"], name="material_re_project_28f38b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["created_by", "status"], name="material_re_created_c566e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["current_approver", "status"],
                name="material_re_current_c3c767_idx",
            ),
        ),
    ]
