# Generated by Django 4.2.16 on 2025-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Ожидает доставки"),
                    ("PARTIAL", "Частично доставлено"),
                    ("DELIVERED", "Полностью доставлено"),
                    ("RECEIVED", "Принято на объекте"),
                ],
                default="PENDING",
                help_text="Статус доставки конкретной позиции",
                max_length=20,
                verbose_name="Статус позиции",
            ),
        ),
    ]
