# Generated by Django 4.2.16 on 2025-11-13 15:17

from django.db import migrations, models


def add_status_field_if_not_exists(apps, schema_editor):
    """
    Добавляет поле status только если оно ещё не существует.
    Это предотвращает ошибку при повторном запуске миграции.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли столбец status в таблице material_request_items
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='material_request_items'
            AND column_name='status'
        """)

        if cursor.fetchone() is None:
            # Столбец не существует, добавляем его
            cursor.execute("""
                ALTER TABLE material_request_items
                ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
            """)
            print("✅ Столбец 'status' успешно добавлен")
        else:
            print("ℹ️ Столбец 'status' уже существует, пропускаем добавление")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_status_field_if_not_exists, migrations.RunPython.noop),
    ]
