# Generated by Django 4.2.16 on 2025-10-18 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("material_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                help_text="Указывается при отмене позиции",
                verbose_name="Причина отмены",
            ),
        ),
        migrations.AddField(
            model_name="materialrequestitem",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отмены"
            ),
        ),
        migrations.AddField(
            model_name="materialrequestitem",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_material_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отменил",
            ),
        ),
        migrations.AddField(
            model_name="materialrequestitem",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активна"), ("CANCELLED", "Отменена")],
                default="ACTIVE",
                max_length=20,
                verbose_name="Статус позиции",
            ),
        ),
    ]
