# Generated by Django 4.2.16 on 2025-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0002_add_status_to_material_request_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequesthistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создана"),
                    ("SUBMITTED", "Отправлена на согласование"),
                    ("APPROVED", "Согласована"),
                    ("REJECTED", "Возвращена на доработку"),
                    ("PAYMENT", "Переведена на оплату"),
                    ("PAID", "Оплачена"),
                    ("DELIVERY", "Переведена на доставку"),
                    ("DELIVERED", "Обновлено фактическое количество"),
                    ("ITEM_RECEIVED", "Позиция принята на объекте"),
                    ("RECEIVED", "Материалы приняты"),
                    ("COMPLETED", "Завершена"),
                ],
                max_length=20,
                verbose_name="Действие",
            ),
        ),
    ]
