# Generated by Django 4.2.16 on 2025-11-13 17:36

from django.db import migrations, models


def add_received_at_field_if_not_exists(apps, schema_editor):
    """
    Добавляет поле received_at только если оно ещё не существует.
    Это предотвращает ошибку при повторном запуске миграции.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли столбец received_at в таблице material_request_items
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='material_request_items'
            AND column_name='received_at'
        """)

        if cursor.fetchone() is None:
            # Столбец не существует, добавляем его
            cursor.execute("""
                ALTER TABLE material_request_items
                ADD COLUMN received_at TIMESTAMP NULL
            """)
            print("✅ Столбец 'received_at' успешно добавлен")
        else:
            print("ℹ️ Столбец 'received_at' уже существует, пропускаем добавление")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0003_add_history_actions"),
    ]

    operations = [
        migrations.RunPython(add_received_at_field_if_not_exists, migrations.RunPython.noop),
    ]
