# Generated by Django 4.2.16 on 2025-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0003_add_history_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда позиция была принята на объекте (статус RECEIVED)",
                null=True,
                verbose_name="Дата принятия",
            ),
        ),
    ]
