# Generated by Django 4.2.16 on 2025-10-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0003_alter_materialrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Ожидает согласования"),
                    ("APPROVED", "Согласовано"),
                    ("REJECTED", "Отклонено"),
                    ("REWORK", "На доработке"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус согласования",
            ),
        ),
    ]
