# Generated by Django 4.2.16 on 2025-10-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0004_materialrequestitem_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("NOT_CHECKED", "Не проверено"),
                    ("IN_STOCK", "В наличии"),
                    ("PARTIALLY_IN_STOCK", "Частично в наличии"),
                    ("OUT_OF_STOCK", "Нет на складе"),
                ],
                default="NOT_CHECKED",
                help_text="Статус проверки наличия материала на складе",
                max_length=30,
                verbose_name="Наличие на складе",
            ),
        ),
        migrations.AddField(
            model_name="materialrequestitem",
            name="available_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Указывается при частичном наличии на складе",
                max_digits=10,
                null=True,
                verbose_name="Количество в наличии",
            ),
        ),
    ]
