# Generated by Django 4.2.16 on 2025-11-13 17:56

from django.db import migrations, models


def add_constraint_if_not_exists(apps, schema_editor):
    """
    Добавляет unique constraint только если он ещё не существует.
    Это предотвращает ошибку при повторном запуске миграции.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли constraint unique_request_number_per_company
        cursor.execute("""
            SELECT constraint_name
            FROM information_schema.table_constraints
            WHERE table_name='material_requests'
            AND constraint_name='unique_request_number_per_company'
        """)

        if cursor.fetchone() is None:
            # Constraint не существует, добавляем его
            # Проверяем имя столбца company (может быть company_id)
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='material_requests'
                AND column_name LIKE 'company%'
            """)
            company_column = cursor.fetchone()
            if company_column:
                company_col_name = company_column[0]
                cursor.execute(f"""
                    ALTER TABLE material_requests
                    ADD CONSTRAINT unique_request_number_per_company
                    UNIQUE ({company_col_name}, request_number)
                """)
            else:
                raise Exception("Не найден столбец company в таблице material_requests")
            print("✅ Constraint 'unique_request_number_per_company' успешно добавлен")
        else:
            print("ℹ️ Constraint 'unique_request_number_per_company' уже существует, пропускаем добавление")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0004_materialrequestitem_received_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="request_number",
            field=models.CharField(
                editable=False,
                help_text="Автогенерируемый номер в формате ДДММГГГГ-№ (уникален в рамках компании)",
                max_length=50,
                verbose_name="Номер заявки",
            ),
        ),
        migrations.RunPython(add_constraint_if_not_exists, migrations.RunPython.noop),
    ]
