# Generated by Django 4.2.16 on 2025-11-13 17:56

from django.db import migrations, models


def add_constraint_if_not_exists(apps, schema_editor):
    """
    Добавляет unique constraint только если он ещё не существует.
    Это предотвращает ошибку при повторном запуске миграции.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Реальное имя таблицы определено в models.py Meta.db_table
        table_name = 'material_requests'

        # Проверяем, существует ли constraint unique_request_number_per_company
        cursor.execute("""
            SELECT constraint_name
            FROM information_schema.table_constraints
            WHERE table_name=%s
            AND constraint_name='unique_request_number_per_company'
        """, [table_name])

        if cursor.fetchone() is None:
            # Constraint не существует, добавляем его
            # Проверяем наличие столбца company_id
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name=%s
                AND column_name = 'company_id'
            """, [table_name])
            company_column = cursor.fetchone()
            if company_column:
                # Добавляем constraint на уникальность (company_id, request_number)
                # Это обеспечивает уникальность номера заявки в рамках компании
                cursor.execute(
                    f'ALTER TABLE {table_name} '
                    f'ADD CONSTRAINT unique_request_number_per_company '
                    f'UNIQUE (company_id, request_number)'
                )
                print("✅ Constraint 'unique_request_number_per_company' успешно добавлен")
            else:
                print(f"ℹ️ Столбец company_id не найден в таблице {table_name}, пропускаем добавление constraint")
        else:
            print("ℹ️ Constraint 'unique_request_number_per_company' уже существует, пропускаем добавление")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0004_materialrequestitem_received_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="request_number",
            field=models.CharField(
                editable=False,
                help_text="Автогенерируемый номер в формате ДДММГГГГ-№ (уникален в рамках компании)",
                max_length=50,
                verbose_name="Номер заявки",
            ),
        ),
        migrations.RunPython(add_constraint_if_not_exists, migrations.RunPython.noop),
    ]
