# Generated by Django 4.2.16 on 2025-11-14
"""
Безопасная миграция для добавления поля status к MaterialRequestItem.

Эта миграция заменяет небезопасную миграцию 0002, которая использовала
ALTER TABLE ... ADD COLUMN ... NOT NULL, что вызывает полную блокировку таблицы.

Безопасный подход (в 3 этапа):
1. Добавить nullable столбец (быстро, без блокировки)
2. Обновить данные батчами (без долгой блокировки)
3. Добавить NOT NULL constraint (быстро)
"""

from django.db import migrations


def add_status_field_safe(apps, schema_editor):
    """
    Безопасное добавление поля status для production.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли столбец status
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='material_request_items'
            AND column_name='status'
        """)

        if cursor.fetchone() is not None:
            print("ℹ️  Столбец 'status' уже существует, пропускаем добавление")
            return

        # ШАГ 1: Добавляем nullable столбец (быстро, без блокировки)
        print("📝 Шаг 1/3: Добавление nullable столбца 'status'...")
        cursor.execute("""
            ALTER TABLE material_request_items
            ADD COLUMN status VARCHAR(20) NULL
        """)

        # ШАГ 2: Обновляем данные батчами для минимизации блокировки
        print("📝 Шаг 2/3: Обновление существующих записей батчами...")
        batch_size = 1000
        updated = 0

        while True:
            cursor.execute(f"""
                UPDATE material_request_items
                SET status = 'PENDING'
                WHERE status IS NULL
                AND id IN (
                    SELECT id FROM material_request_items
                    WHERE status IS NULL
                    LIMIT {batch_size}
                )
            """)
            rows_updated = cursor.rowcount
            updated += rows_updated
            print(f"   Обновлено записей: {updated}")

            if rows_updated < batch_size:
                break

        # ШАГ 3: Добавляем NOT NULL constraint (быстро)
        print("📝 Шаг 3/3: Добавление NOT NULL constraint...")
        cursor.execute("""
            ALTER TABLE material_request_items
            ALTER COLUMN status SET NOT NULL
        """)

        # ШАГ 4: Добавляем DEFAULT для будущих записей
        cursor.execute("""
            ALTER TABLE material_request_items
            ALTER COLUMN status SET DEFAULT 'PENDING'
        """)

        print("✅ Столбец 'status' успешно добавлен безопасным методом")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0005_alter_materialrequest_request_number_and_more"),
    ]

    operations = [
        migrations.RunPython(add_status_field_safe, migrations.RunPython.noop),
    ]
