# Generated by Django 4.2.16 on 2025-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0006_alter_materialrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("UNDER_REVIEW", "На проверке снабжения"),
                    ("WAREHOUSE_CHECK", "Центр склад"),
                    ("BACK_TO_SUPPLY", "Снабжение"),
                    ("PROJECT_MANAGER_APPROVAL", "У руководителя проекта"),
                    ("DIRECTOR_APPROVAL", "У директора"),
                    ("REWORK", "На доработке"),
                    ("APPROVED", "Согласовано"),
                    ("SENT_TO_SITE", "Отправить на объект (у зав.склада)"),
                    ("WAREHOUSE_SHIPPING", "Отправлено на объект (у автора)"),
                    ("PAYMENT", "На оплате"),
                    ("PAID", "Оплачено"),
                    ("DELIVERY", "Доставлено"),
                    ("COMPLETED", "Отработано"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
