# Generated by Django 4.2.16 on 2025-11-14
"""
Безопасное добавление составных индексов БЕЗ блокировки таблицы.

Для production используется CONCURRENTLY для создания индексов без downtime.
Это критично для масштабируемого многопользовательского сервиса.

ВАЖНО: После применения миграции раскомментировать индексы в models.py!
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0006_safe_add_status_field"),
    ]

    operations = [
        # ВАЖНО: Для PostgreSQL создаем индексы через SQL с CONCURRENTLY
        # Это позволяет создавать индексы БЕЗ блокировки таблицы
        migrations.RunSQL(
            sql=[
                # 1. Индекс для фильтрации по компании + статусу + soft delete
                """
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_company_status_deleted
                ON material_requests (company_id, status, is_deleted);
                """,

                # 2. Индекс для фильтрации по компании + роли согласующего
                """
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_company_approval_role
                ON material_requests (company_id, current_approval_role);
                """,

                # 3. Индекс для фильтрации по проекту + статусу
                """
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_project_status
                ON material_requests (project_id, status);
                """,

                # 4. Индекс для фильтрации по автору + дате создания (DESC)
                """
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_author_created
                ON material_requests (author_id, created_at DESC);
                """,
            ],
            reverse_sql=[
                "DROP INDEX CONCURRENTLY IF EXISTS idx_company_status_deleted;",
                "DROP INDEX CONCURRENTLY IF EXISTS idx_company_approval_role;",
                "DROP INDEX CONCURRENTLY IF EXISTS idx_project_status;",
                "DROP INDEX CONCURRENTLY IF EXISTS idx_author_created;",
            ],
        ),
    ]
