# Generated by Django 4.2.16 on 2025-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0006_safe_add_status_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда позиция была принята на объекте (статус RECEIVED)",
                null=True,
                verbose_name="Дата принятия",
            ),
        ),
        migrations.AddField(
            model_name="materialrequestitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Ожидает доставки"),
                    ("PARTIAL", "Частично доставлено"),
                    ("DELIVERED", "Полностью доставлено"),
                    ("RECEIVED", "Принято на объекте"),
                ],
                default="PENDING",
                help_text="Статус доставки конкретной позиции",
                max_length=20,
                verbose_name="Статус позиции",
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["company", "status", "is_deleted"],
                name="idx_company_status_deleted",
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["company", "current_approval_role"],
                name="idx_company_approval_role",
            ),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(fields=["project", "status"], name="idx_project_status"),
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(
                fields=["author", "-created_at"], name="idx_author_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialrequest",
            constraint=models.UniqueConstraint(
                fields=("company", "request_number"),
                name="unique_request_number_per_company",
            ),
        ),
    ]
