# Generated by Django 4.2.16 on 2025-11-14
"""
Безопасное добавление поля company к MaterialRequest.

Эта миграция добавляет поле company_id, которое дублирует project.company
для оптимизации запросов и индексации.

Безопасный подход (в 3 этапа):
1. Добавить nullable столбец (быстро, без блокировки)
2. Заполнить данные из project.company батчами (без долгой блокировки)
3. Добавить NOT NULL constraint и foreign key (быстро)
"""

from django.db import migrations, models
import django.db.models.deletion


def populate_company_from_project(apps, schema_editor):
    """
    Заполняет поле company значениями из project.company.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли столбец company_id
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='material_requests'
            AND column_name='company_id'
        """)

        if cursor.fetchone() is None:
            print("ℹ️  Столбец 'company_id' не существует, пропускаем заполнение")
            return

        # Заполняем company_id из project.company батчами
        print("📝 Заполнение company_id из project.company...")
        cursor.execute("""
            UPDATE material_requests mr
            SET company_id = p.company_id
            FROM projects p
            WHERE mr.project_id = p.id
            AND mr.company_id IS NULL
        """)
        updated_rows = cursor.rowcount
        print(f"✅ Обновлено записей: {updated_rows}")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0007_add_composite_indexes_concurrently"),
        ("users", "0001_initial"),  # Зависимость от модели Company
    ]

    operations = [
        # ШАГ 1: Добавляем nullable поле company
        migrations.AddField(
            model_name='materialrequest',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='material_requests',
                to='users.company',
                verbose_name='Компания',
                help_text='Компания, создавшая заявку',
                db_index=True,
            ),
        ),

        # ШАГ 2: Заполняем данные из project.company
        migrations.RunPython(
            populate_company_from_project,
            migrations.RunPython.noop
        ),

        # ШАГ 3: Делаем поле NOT NULL
        migrations.AlterField(
            model_name='materialrequest',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='material_requests',
                to='users.company',
                verbose_name='Компания',
                help_text='Компания, создавшая заявку',
                db_index=True,
            ),
        ),
    ]
