# Generated by Django 4.2.16 on 2025-11-14
"""
Безопасное добавление поля company к MaterialRequest.

Эта миграция добавляет поле company_id, которое дублирует project.company
для оптимизации запросов и индексации.

Безопасный подход (в 3 этапа):
1. Добавить nullable столбец (быстро, без блокировки)
2. Заполнить данные из project.company батчами (без долгой блокировки)
3. Добавить NOT NULL constraint и foreign key (быстро)
"""

from django.db import migrations, models
import django.db.models.deletion


def populate_company_from_project(apps, schema_editor):
    """
    Заполняет поле company значениями из project.company.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли столбец company_id
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='material_requests'
            AND column_name='company_id'
        """)

        if cursor.fetchone() is None:
            print("ℹ️  Столбец 'company_id' не существует, пропускаем заполнение")
            return

        # Заполняем company_id из project.company батчами
        print("📝 Заполнение company_id из project.company...")
        cursor.execute("""
            UPDATE material_requests mr
            SET company_id = p.company_id
            FROM projects_project p
            WHERE mr.project_id = p.id
            AND mr.company_id IS NULL
        """)
        updated_rows = cursor.rowcount
        print(f"✅ Обновлено записей: {updated_rows}")


def add_company_field_if_not_exists(apps, schema_editor):
    """
    Добавляет поле company только если его нет.
    Это обеспечивает идемпотентность миграции.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, существует ли столбец company_id
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='material_requests'
            AND column_name='company_id'
        """)

        if cursor.fetchone() is not None:
            print("ℹ️  Столбец 'company_id' уже существует, пропускаем добавление")
            return

        # Столбец не существует, добавляем его
        print("📝 Добавление столбца company_id...")
        cursor.execute("""
            ALTER TABLE material_requests
            ADD COLUMN company_id INTEGER NULL
            REFERENCES users_company(id)
            ON DELETE CASCADE
        """)

        # Создаем индекс
        cursor.execute("""
            CREATE INDEX material_requests_company_id_idx
            ON material_requests (company_id)
        """)
        print("✅ Столбец company_id добавлен")


def make_company_not_null(apps, schema_editor):
    """
    Делает поле company NOT NULL только если оно nullable.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Проверяем, является ли столбец nullable
        cursor.execute("""
            SELECT is_nullable
            FROM information_schema.columns
            WHERE table_name='material_requests'
            AND column_name='company_id'
        """)

        result = cursor.fetchone()
        if result is None:
            print("⚠️  Столбец company_id не существует")
            return

        is_nullable = result[0]
        if is_nullable == 'NO':
            print("ℹ️  Столбец company_id уже NOT NULL, пропускаем")
            return

        # Делаем NOT NULL
        print("📝 Установка NOT NULL для company_id...")
        cursor.execute("""
            ALTER TABLE material_requests
            ALTER COLUMN company_id SET NOT NULL
        """)
        print("✅ Столбец company_id теперь NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0007_add_composite_indexes_concurrently"),
        ("users", "0001_initial"),  # Зависимость от модели Company
    ]

    operations = [
        # ШАГ 1: Добавляем nullable поле company (если его нет)
        migrations.RunPython(
            add_company_field_if_not_exists,
            migrations.RunPython.noop
        ),

        # ШАГ 2: Заполняем данные из project.company
        migrations.RunPython(
            populate_company_from_project,
            migrations.RunPython.noop
        ),

        # ШАГ 3: Делаем поле NOT NULL (если оно еще nullable)
        migrations.RunPython(
            make_company_not_null,
            migrations.RunPython.noop
        ),
    ]
