# Generated by Django 4.2.16 on 2025-11-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0008_add_company_field_safe"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда позиция была принята на объекте (статус RECEIVED)",
                null=True,
                verbose_name="Дата принятия",
            ),
        ),
        migrations.AddField(
            model_name="materialrequestitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Ожидает доставки"),
                    ("PARTIAL", "Частично доставлено"),
                    ("DELIVERED", "Полностью доставлено"),
                    ("RECEIVED", "Принято на объекте"),
                ],
                default="PENDING",
                help_text="Статус доставки конкретной позиции",
                max_length=20,
                verbose_name="Статус позиции",
            ),
        ),
    ]
