# Generated by Django 4.2.16 on 2025-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0008_materialrequestitem_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequestitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("UNDER_REVIEW", "Снабжение (проверка)"),
                    ("WAREHOUSE_CHECK", "Завсклад"),
                    ("BACK_TO_SUPPLY", "Снабжение (после склада)"),
                    ("ENGINEER_APPROVAL", "Инженер ПТО"),
                    ("BACK_TO_SUPPLY_AFTER_ENGINEER", "Снабжение (после инженера)"),
                    ("PROJECT_MANAGER_APPROVAL", "Руководитель проекта"),
                    ("BACK_TO_SUPPLY_AFTER_PM", "Снабжение (после рук.проекта)"),
                    ("DIRECTOR_APPROVAL", "Директор"),
                    ("BACK_TO_SUPPLY_AFTER_DIRECTOR", "Снабжение (после директора)"),
                    ("REWORK", "На доработке"),
                    ("APPROVED", "Согласовано"),
                    ("SENT_TO_SITE", "Отправить на объект (у зав.склада)"),
                    ("WAREHOUSE_SHIPPING", "Отправлено на объект (у автора)"),
                    ("PAYMENT", "На оплате"),
                    ("PAID", "Оплачено"),
                    ("DELIVERY", "Доставлено"),
                    ("COMPLETED", "Отработано"),
                ],
                default="DRAFT",
                help_text="Независимый статус движения позиции материала по процессу согласования",
                max_length=30,
                verbose_name="Статус позиции в процессе",
            ),
        ),
    ]
