# Generated by Django 4.2.16 on 2025-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0010_add_returned_for_revision_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="actual_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фактическое количество, полученное на объекте (заполняется автором после доставки)",
                max_digits=10,
                null=True,
                verbose_name="Количество по факту",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequestitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Количество по заявке"
            ),
        ),
    ]
