# Generated by Django 4.2.16 on 2025-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0011_materialrequestitem_actual_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="previous_item_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Черновик"),
                    ("UNDER_REVIEW", "Снабжение (проверка)"),
                    ("WAREHOUSE_CHECK", "Завсклад"),
                    ("BACK_TO_SUPPLY", "Снабжение (после склада)"),
                    ("ENGINEER_APPROVAL", "Инженер ПТО"),
                    ("BACK_TO_SUPPLY_AFTER_ENGINEER", "Снабжение (после инженера)"),
                    ("PROJECT_MANAGER_APPROVAL", "Руководитель проекта"),
                    ("BACK_TO_SUPPLY_AFTER_PM", "Снабжение (после рук.проекта)"),
                    ("DIRECTOR_APPROVAL", "Директор"),
                    ("BACK_TO_SUPPLY_AFTER_DIRECTOR", "Снабжение (после директора)"),
                    ("RETURNED_FOR_REVISION", "На доработке (у автора)"),
                    ("REWORK", "На доработке"),
                    ("APPROVED", "Согласовано"),
                    ("SENT_TO_SITE", "Отправить на объект (у зав.склада)"),
                    ("WAREHOUSE_SHIPPING", "Отправлено на объект (у автора)"),
                    ("PAYMENT", "На оплате"),
                    ("PAID", "Оплачено"),
                    ("DELIVERY", "Доставлено"),
                    ("COMPLETED", "Отработано"),
                ],
                help_text="Сохраняется при отмене для возможности восстановления позиции на том же этапе согласования",
                max_length=30,
                null=True,
                verbose_name="Предыдущий статус позиции",
            ),
        ),
    ]
