# Generated by Django 4.2.16 on 2025-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0012_add_previous_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="issued_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Количество материала, выданное со склада (заполняется завскладом)",
                max_digits=10,
                null=True,
                verbose_name="Выдано",
            ),
        ),
    ]
