# Generated by Django 4.2.16 on 2025-10-22 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("material_requests", "0013_add_issued_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, который последний изменил количество выдано",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_materials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Изменил",
            ),
        ),
    ]
