# Generated by Django 4.2.16 on 2025-11-01 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("material_requests", "0014_add_issued_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Дата и время когда запись была удалена",
                null=True,
                verbose_name="Дата удаления",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, удаливший запись",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалил",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Запись помечена как удаленная (soft delete)",
                verbose_name="Удалено",
            ),
        ),
    ]
