# Generated by Django 4.2.16 on 2025-11-03 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_user_archived_user_deleted_at_user_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("material_requests", "0015_materialrequest_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Например: "Основная схема согласования"',
                        max_length=255,
                        verbose_name="Название схемы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание схемы согласования",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Только одна схема может быть активной в компании",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_flow_templates",
                        to="users.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_approval_flows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон цепочки согласования",
                "verbose_name_plural": "Шаблоны цепочек согласования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Директор"),
                            ("CHIEF_ENGINEER", "Главный инженер"),
                            ("PROJECT_MANAGER", "Руководитель проекта"),
                            ("ENGINEER", "Инженер ПТО"),
                            ("SITE_MANAGER", "Начальник участка"),
                            ("FOREMAN", "Прораб"),
                            ("SUPPLY_MANAGER", "Снабженец"),
                            ("WAREHOUSE_HEAD", "Завсклад центрального склада"),
                            ("SITE_WAREHOUSE_MANAGER", "Завсклад объекта"),
                        ],
                        help_text="Кто должен согласовать на этом этапе",
                        max_length=50,
                        verbose_name="Роль согласующего",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Порядок согласования (1, 2, 3...)",
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "skip_if_empty",
                    models.BooleanField(
                        default=True,
                        help_text="Автоматически пропускать этот этап, если в проекте нет пользователя с указанной ролью",
                        verbose_name="Пропустить, если нет пользователя",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Можно ли пропустить этот этап вручную",
                        verbose_name="Обязательный этап",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о том, что проверяется на этом этапе",
                        verbose_name="Описание этапа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "flow_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="material_requests.approvalflowtemplate",
                        verbose_name="Цепочка согласования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап согласования",
                "verbose_name_plural": "Этапы согласования",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("IN_PROGRESS", "На согласовании"),
                    ("APPROVED", "Согласовано"),
                    ("REJECTED", "Отклонено"),
                    ("COMPLETED", "Выполнено"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="CompanyApprovalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_manage_approval_flow",
                    models.BooleanField(
                        default=False,
                        help_text="Разрешено ли компании настраивать свою цепочку согласования (устанавливает суперадмин)",
                        verbose_name="Доступ к настройке цепочки согласования",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "approval_flow_managers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Пользователи компании, которые могут настраивать цепочку согласования",
                        related_name="managed_approval_flows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджеры цепочек",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_settings",
                        to="users.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки согласования компании",
                "verbose_name_plural": "Настройки согласования компаний",
            },
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                help_text="На каком этапе цепочки согласования находится заявка",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_material_requests",
                to="material_requests.approvalstep",
                verbose_name="Текущий этап согласования",
            ),
        ),
        migrations.CreateModel(
            name="MaterialRequestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает согласования"),
                            ("APPROVED", "Согласовано"),
                            ("REJECTED", "Отклонено"),
                            ("SKIPPED", "Пропущено"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус согласования",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий при согласовании или отклонении",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время согласования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, который должен согласовать (может быть NULL если этап пропущен)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_request_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Согласующий",
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="material_requests.materialrequest",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="material_requests.approvalstep",
                        verbose_name="Этап согласования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласование заявки",
                "verbose_name_plural": "Согласования заявок",
                "ordering": ["step__order"],
                "indexes": [
                    models.Index(
                        fields=["material_request", "step"],
                        name="material_re_materia_0560dd_idx",
                    ),
                    models.Index(
                        fields=["approver", "status"],
                        name="material_re_approve_ba433a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["flow_template", "order"], name="material_re_flow_te_d3e289_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalstep",
            unique_together={("flow_template", "order")},
        ),
        migrations.AddConstraint(
            model_name="approvalflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company", "is_active"),
                name="unique_active_flow_per_company",
            ),
        ),
    ]
