# Generated by Django 4.2 on 2025-11-09
# Миграция для упрощения ProcessStatus и конвертации старых статусов

from django.db import migrations, models


def migrate_item_statuses_forward(apps, schema_editor):
    """
    Конвертирует старые статусы позиций в новые упрощенные статусы.

    Маппинг старых статусов на новые:
    - Все статусы согласования (UNDER_REVIEW, WAREHOUSE_CHECK, *_APPROVAL, BACK_TO_SUPPLY*) → IN_APPROVAL
    - APPROVED → PAYMENT (после согласования → на оплату)
    - PAID → DELIVERY (оплачено → на доставке)
    - SENT_TO_SITE, WAREHOUSE_SHIPPING → DELIVERY
    - REWORK → RETURNED_FOR_REVISION
    - DRAFT, PAYMENT, DELIVERY, COMPLETED → остаются как есть
    """
    MaterialRequestItem = apps.get_model('material_requests', 'MaterialRequestItem')

    # Маппинг старых статусов на новые
    STATUS_MAPPING = {
        # Согласование → На согласовании
        'UNDER_REVIEW': 'IN_APPROVAL',
        'WAREHOUSE_CHECK': 'IN_APPROVAL',
        'BACK_TO_SUPPLY': 'IN_APPROVAL',
        'ENGINEER_APPROVAL': 'IN_APPROVAL',
        'BACK_TO_SUPPLY_AFTER_ENGINEER': 'IN_APPROVAL',
        'PROJECT_MANAGER_APPROVAL': 'IN_APPROVAL',
        'BACK_TO_SUPPLY_AFTER_PM': 'IN_APPROVAL',
        'DIRECTOR_APPROVAL': 'IN_APPROVAL',
        'BACK_TO_SUPPLY_AFTER_DIRECTOR': 'IN_APPROVAL',

        # Доработка → На доработке
        'REWORK': 'RETURNED_FOR_REVISION',

        # После согласования → На оплату
        'APPROVED': 'PAYMENT',

        # Отправка на объект → На доставке
        'SENT_TO_SITE': 'DELIVERY',
        'WAREHOUSE_SHIPPING': 'DELIVERY',

        # Оплачено → На доставке
        'PAID': 'DELIVERY',

        # Остаются как есть
        'DRAFT': 'DRAFT',
        'RETURNED_FOR_REVISION': 'RETURNED_FOR_REVISION',
        'PAYMENT': 'PAYMENT',
        'DELIVERY': 'DELIVERY',
        'COMPLETED': 'COMPLETED',
    }

    # Подсчет статистики
    stats = {}
    total_converted = 0

    # Конвертация статусов
    for old_status, new_status in STATUS_MAPPING.items():
        count = MaterialRequestItem.objects.filter(
            item_status=old_status
        ).update(item_status=new_status)

        if count > 0:
            stats[f'{old_status} → {new_status}'] = count
            total_converted += count

    # Вывод статистики
    if stats:
        print(f'\n✅ Конвертировано {total_converted} позиций:')
        for transition, count in stats.items():
            print(f'   {transition}: {count} шт.')
    else:
        print('\n✓ Нет позиций для конвертации (база данных пустая или уже обновлена)')


def migrate_item_statuses_backward(apps, schema_editor):
    """
    Обратная миграция - пытается восстановить старые статусы.
    ВНИМАНИЕ: Полное восстановление невозможно, т.к. несколько старых статусов
    маппятся на один новый. Восстанавливаем в наиболее вероятный статус.
    """
    MaterialRequestItem = apps.get_model('material_requests', 'MaterialRequestItem')

    # Обратный маппинг (выбираем наиболее общий статус)
    REVERSE_STATUS_MAPPING = {
        'IN_APPROVAL': 'UNDER_REVIEW',  # Берем первый в цепочке согласования
        'PAYMENT': 'PAYMENT',           # Остается как есть
        'DELIVERY': 'DELIVERY',         # Остается как есть
        'COMPLETED': 'COMPLETED',       # Остается как есть
        'RETURNED_FOR_REVISION': 'RETURNED_FOR_REVISION',  # Остается как есть
        'DRAFT': 'DRAFT',               # Остается как есть
    }

    for new_status, old_status in REVERSE_STATUS_MAPPING.items():
        MaterialRequestItem.objects.filter(
            item_status=new_status
        ).update(item_status=old_status)

    print('\n⚠️  Обратная миграция выполнена с потерей детализации статусов согласования')


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0016_approvalflowtemplate_approvalstep_and_more'),
    ]

    operations = [
        # 1. Сначала конвертируем существующие данные
        migrations.RunPython(
            migrate_item_statuses_forward,
            migrate_item_statuses_backward
        ),

        # 2. Затем изменяем choices в модели
        migrations.AlterField(
            model_name='materialrequestitem',
            name='item_status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Черновик'),
                    ('IN_APPROVAL', 'На согласовании'),
                    ('RETURNED_FOR_REVISION', 'На доработке'),
                    ('PAYMENT', 'На оплате'),
                    ('DELIVERY', 'На доставке'),
                    ('COMPLETED', 'Отработано'),
                    ('CANCELLED', 'Отменено')
                ],
                default='DRAFT',
                max_length=50,
                verbose_name='Статус позиции в процессе'
            ),
        ),
    ]
