# Generated by Django 4.2.16 on 2025-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material_requests", "0017_simplify_process_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="role",
            field=models.CharField(
                choices=[
                    ("DIRECTOR", "Директор"),
                    ("CHIEF_ENGINEER", "Главный инженер"),
                    ("PROJECT_MANAGER", "Руководитель проекта"),
                    ("CHIEF_POWER_ENGINEER", "Главный энергетик"),
                    ("ENGINEER", "Инженер ПТО"),
                    ("SITE_MANAGER", "Начальник участка"),
                    ("FOREMAN", "Прораб"),
                    ("POWER_ENGINEER", "Энергетик"),
                    ("SUPPLY_MANAGER", "Снабженец"),
                    ("WAREHOUSE_HEAD", "Завсклад центрального склада"),
                    ("SITE_WAREHOUSE_MANAGER", "Завсклад объекта"),
                ],
                help_text="Кто должен согласовать на этом этапе",
                max_length=50,
                verbose_name="Роль согласующего",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequestitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("IN_APPROVAL", "На согласовании"),
                    ("RETURNED_FOR_REVISION", "На доработке"),
                    ("PAYMENT", "На оплате"),
                    ("DELIVERY", "На доставке"),
                    ("COMPLETED", "Отработано"),
                    ("CANCELLED", "Отменено"),
                ],
                default="DRAFT",
                help_text="Независимый статус движения позиции материала по процессу согласования",
                max_length=30,
                verbose_name="Статус позиции в процессе",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequestitem",
            name="previous_item_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Черновик"),
                    ("IN_APPROVAL", "На согласовании"),
                    ("RETURNED_FOR_REVISION", "На доработке"),
                    ("PAYMENT", "На оплате"),
                    ("DELIVERY", "На доставке"),
                    ("COMPLETED", "Отработано"),
                    ("CANCELLED", "Отменено"),
                ],
                help_text="Сохраняется при отмене для возможности восстановления позиции на том же этапе согласования",
                max_length=30,
                null=True,
                verbose_name="Предыдущий статус позиции",
            ),
        ),
    ]
