# Generated by Django 4.2.16 on 2025-11-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_user_role"),
        ("material_requests", "0018_alter_approvalstep_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalflowtemplate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Компания (NULL для глобальных настроек)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_flow_templates",
                to="users.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="approvalflowtemplate",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Только одна глобальная схема или одна схема на компанию может быть активной",
                verbose_name="Активна",
            ),
        ),
    ]
