# Generated by Django 4.2.16 on 2025-11-05 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_project_deleted_at_project_deleted_by_and_more"),
        ("users", "0019_remove_user_archived_user_deleted_at_user_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_number",
                    models.CharField(
                        editable=False,
                        help_text="Автогенерируемый номер в формате TASK-YYYYMMDD-XXX",
                        max_length=50,
                        unique=True,
                        verbose_name="Номер задачи",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Краткое название задачи",
                        max_length=255,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Полное описание задачи с деталями",
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Автоматически устанавливается при создании",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Автоматически обновляется при изменении",
                        verbose_name="Дата изменения",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        help_text="Дедлайн выполнения задачи",
                        verbose_name="Срок исполнения",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Устанавливается при отметке задачи как выполненной",
                        null=True,
                        verbose_name="Дата выполнения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "В исполнении"),
                            ("COMPLETED", "Исполнено"),
                            ("OVERDUE", "Просрочено"),
                            ("REJECTED", "Отклонено"),
                        ],
                        default="IN_PROGRESS",
                        help_text="Текущий статус задачи",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Обязательно при отмене задачи",
                        null=True,
                        verbose_name="Причина отклонения",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отклонения"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время перемещения в корзину",
                        null=True,
                        verbose_name="Удалено",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="True если задача в корзине",
                        verbose_name="В корзине",
                    ),
                ),
                (
                    "assigned_to_contractor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Исполнитель - подрядчик",
                        limit_choices_to={"role": "CONTRACTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_contractor_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кому (подрядчик)",
                    ),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Исполнитель - сотрудник",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_user_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кому (сотрудник)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Компания, к которой относится задача",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="users.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь, создавший задачу",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="От кого",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Проект, к которому относится задача (опционально)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "db_table": "tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_number"], name="tasks_task_nu_eff004_idx"
                    ),
                    models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
                    models.Index(fields=["deadline"], name="tasks_deadlin_7f16a6_idx"),
                    models.Index(
                        fields=["created_by"], name="tasks_created_816ff3_idx"
                    ),
                    models.Index(
                        fields=["assigned_to_user"], name="tasks_assigne_56af05_idx"
                    ),
                    models.Index(
                        fields=["assigned_to_contractor"],
                        name="tasks_assigne_5467f0_idx",
                    ),
                    models.Index(fields=["company"], name="tasks_company_a05724_idx"),
                    models.Index(
                        fields=["is_deleted"], name="tasks_is_dele_8a1818_idx"
                    ),
                ],
            },
        ),
    ]
