# Generated by Django 4.2.16 on 2025-11-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to_contractor",
            field=models.ForeignKey(
                blank=True,
                help_text='Исполнитель - подрядчик. При удалении подрядчика задача переходит в статус "Просрочено"',
                limit_choices_to={"role": "CONTRACTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_contractor_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кому (подрядчик)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to_user",
            field=models.ForeignKey(
                blank=True,
                help_text='Исполнитель - сотрудник. При удалении исполнителя задача переходит в статус "Просрочено"',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_user_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кому (сотрудник)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text='Пользователь, создавший задачу. При удалении создателя задача остается в статусе "В процессе"',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="От кого",
            ),
        ),
    ]
