# Generated by Django 4.2.16 on 2025-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_fix_cascade_delete_preserve_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Полное описание задачи с деталями (опционально)",
                null=True,
                verbose_name="Описание задачи",
            ),
        ),
    ]
