# Generated by Django 4.2.16 on 2025-10-16 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Файл технического условия в формате PDF",
                        upload_to="technical_conditions/%Y/%m/",
                        verbose_name="PDF файл",
                    ),
                ),
                (
                    "received_from",
                    models.CharField(
                        help_text="Организация, выдавшая техническое условие (например: Водоканал, Телеком, Электросеть)",
                        max_length=255,
                        verbose_name="От кого получено",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительное описание технического условия",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_technical_conditions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техническое условие",
                "verbose_name_plural": "Технические условия",
                "ordering": ["-created_at"],
            },
        ),
    ]
