# Generated by Django 4.2.16 on 2025-10-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_company"),
        ("technical_conditions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalcondition",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Проект, к которому относится техническое условие",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technical_conditions",
                to="projects.project",
                verbose_name="Проект",
            ),
        ),
    ]
