# Generated by Django 4.2.16 on 2025-10-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0005_project_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "tender_type",
                    models.CharField(
                        choices=[
                            ("MATERIALS", "Материалы"),
                            ("WORKS", "Работы"),
                            ("EQUIPMENT", "Оборудование"),
                            ("SERVICES", "Услуги"),
                        ],
                        default="MATERIALS",
                        max_length=20,
                        verbose_name="Тип тендера",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PUBLISHED", "Опубликован"),
                            ("IN_PROGRESS", "В процессе"),
                            ("CLOSED", "Закрыт"),
                            ("CANCELLED", "Отменен"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Плановый бюджет в тенге",
                        max_digits=15,
                        null=True,
                        verbose_name="Бюджет",
                    ),
                ),
                (
                    "winning_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Сумма победителя",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tenders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenders",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_tenders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_tenders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тендер",
                "verbose_name_plural": "Тендеры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="tenders/documents/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenders.tender",
                        verbose_name="Тендер",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ тендера",
                "verbose_name_plural": "Документы тендеров",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TenderBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=500, verbose_name="Название компании"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Предложенная сумма",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подана"),
                ),
                (
                    "is_winner",
                    models.BooleanField(default=False, verbose_name="Победитель"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_bids",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участник",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="tenders.tender",
                        verbose_name="Тендер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на тендер",
                "verbose_name_plural": "Заявки на тендеры",
                "ordering": ["amount"],
                "unique_together": {("tender", "participant")},
            },
        ),
    ]
