# Generated by Django 4.2.16 on 2025-10-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="execution_period",
            field=models.CharField(
                blank=True,
                help_text="Например: 30 дней, 2 месяца, до 15.05.2025",
                max_length=200,
                verbose_name="Срок исполнения",
            ),
        ),
    ]
