# Generated by Django 4.2.16 on 2025-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0002_tender_execution_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Город реализации проекта",
                max_length=100,
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Название компании-заказчика",
                max_length=300,
                verbose_name="Компания",
            ),
        ),
    ]
