# Generated by Django 4.2.16 on 2025-10-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenders", "0003_tender_city_tender_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicTenderAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=300, verbose_name="Название компании"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=200, verbose_name="Контактное лицо"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "password",
                    models.CharField(
                        help_text="Хэшированный пароль",
                        max_length=255,
                        verbose_name="Пароль",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает модерации"),
                            ("APPROVED", "Одобрен"),
                            ("REJECTED", "Отклонен"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата одобрения"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний вход"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Причина отклонения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_public_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Одобрил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к публичным тендерам",
                "verbose_name_plural": "Доступы к публичным тендерам",
                "ordering": ["-created_at"],
            },
        ),
    ]
