# Generated by Django 4.2.16 on 2025-11-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenders", "0005_tender_deleted_at_tender_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenderbid",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                help_text="Участник тендера. При удалении участника заявка остается с сохранением company_name",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tender_bids",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участник",
            ),
        ),
    ]
