# Generated by Django 4.2.16 on 2025-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("dashboard", "Дашборд"),
                            ("projects", "Проекты"),
                            ("issues", "Замечания"),
                            ("users", "Сотрудники"),
                            ("contractors", "Подрядчики"),
                            ("supervisions", "Надзоры"),
                            ("technical-conditions", "Техусловия"),
                            ("material-requests", "Заявки"),
                            ("warehouse", "Склад"),
                            ("tenders", "Тендеры"),
                            ("reports", "Отчеты"),
                            ("profile", "Профиль"),
                            ("settings", "Настройки"),
                        ],
                        max_length=50,
                        verbose_name="Страница",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Директор"),
                            ("CHIEF_ENGINEER", "Гл.инженер"),
                            ("PROJECT_MANAGER", "Рук.проекта"),
                            ("ENGINEER", "Инженер ПТО"),
                            ("SITE_MANAGER", "Нач.участка"),
                            ("FOREMAN", "Прораб"),
                            ("MASTER", "Мастер"),
                            ("SUPERVISOR", "Технадзор"),
                            ("CONTRACTOR", "Подрядчик"),
                            ("OBSERVER", "Наблюдатель"),
                            ("SUPPLY_MANAGER", "Снабженец"),
                            ("WAREHOUSE_HEAD", "Зав.склада"),
                            ("SITE_WAREHOUSE_MANAGER", "Завсклад объекта"),
                        ],
                        max_length=50,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "has_access",
                    models.BooleanField(default=False, verbose_name="Есть доступ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Доступ к странице",
                "verbose_name_plural": "Матрица доступа",
                "ordering": ["page", "role"],
                "indexes": [
                    models.Index(
                        fields=["page", "role"], name="settings_pa_page_0b2a01_idx"
                    )
                ],
                "unique_together": {("page", "role")},
            },
        ),
    ]
