# Generated by Django 4.2.16 on 2025-10-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_has_full_access_user_is_company_owner_and_more"),
        ("settings", "0002_add_company_to_pageaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Например: "Прораб стандарт", "Мастер ограниченный"',
                        max_length=100,
                        verbose_name="Название шаблона",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Роль пользователя, для которой предназначен шаблон",
                        max_length=50,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание шаблона и его назначения",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "allowed_pages",
                    models.JSONField(
                        default=list,
                        help_text="Список slug страниц, доступных по этому шаблону",
                        verbose_name="Разрешенные страницы",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Применяется автоматически при создании пользователя с этой ролью",
                        verbose_name="Шаблон по умолчанию",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Шаблон роли",
                "verbose_name_plural": "Шаблоны ролей",
                "ordering": ["company", "role", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="pageaccess",
            new_name="settings_pa_company_8d2f4d_idx",
            old_name="settings_pa_company_bb9a2c_idx",
        ),
        migrations.RenameIndex(
            model_name="pageaccess",
            new_name="settings_pa_company_ee1042_idx",
            old_name="settings_pa_company_b4cf68_idx",
        ),
        migrations.AddField(
            model_name="roletemplate",
            name="company",
            field=models.ForeignKey(
                help_text="Компания, для которой создан шаблон",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_templates",
                to="users.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddIndex(
            model_name="roletemplate",
            index=models.Index(
                fields=["company", "role"], name="settings_ro_company_e548f3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roletemplate",
            unique_together={("company", "name")},
        ),
    ]
