# Generated by Django 4.2.16 on 2025-11-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_roletemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageaccess",
            name="page",
            field=models.CharField(
                choices=[
                    ("dashboard", "Дашборд"),
                    ("projects", "Проекты"),
                    ("issues", "Замечания"),
                    ("users", "Сотрудники"),
                    ("contractors", "Подрядчики"),
                    ("supervisions", "Надзоры"),
                    ("material-requests", "Заявки"),
                    ("warehouse", "Склад"),
                    ("tenders", "Тендеры"),
                    ("reports", "Отчеты"),
                    ("profile", "Профиль"),
                    ("settings", "Настройки"),
                ],
                max_length=50,
                verbose_name="Страница",
            ),
        ),
    ]
