# Generated by Django 4.2.16 on 2025-11-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_remove_technical_conditions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageAccess",
        ),
    ]
